### ISSUE TITLE
Make the operator dictionary normative

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#142]
This was raised by @dani31415 in 2014: 
https://lists.w3.org/Archives/Public/www-math/2014Jan/0014.html

In general the fact that the dictionary is not normative has issues
1. For browser interoperability, we really want things to be well specified and tested. We now have exhaustive WPT tests for the operator dictionary and the section MathML Core is normative: https://mathml-refresh.github.io/mathml-core/#operator-dictionary
2. For tools, as Dani said they end up having to specify explicit operator attributes in order to ensure pages render the same everywhere... which kinda makes the operator dictionary irrelevant...

Should the operator dictionary be normative in MathML Full too? 
Should it just refer to MathML Core?

**Comment by davidcarlisle** [comment]
I don't think we can make it normative for full as by design full allows some flexibility in rendering to map mathml into the "native" typesetting (tex, or Word or maple etc) and still be conformant, and in some cases you need to drop some operator dictionary features.

But for core where we are trying to specify interoperable behaviour on any web platform implementations I agree it should be normative.

**Comment by fred-wang** [comment]
consensus from previous meetings:
- normative in core
- non-normative in full (still need to update the spec to refer to core instead of duplicating it)

**Comment by fred-wang** [comment]
Closing since it's something to be changed in full.
