### ISSUE TITLE
Remove accent property on some operators 

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#151]
See https://github.com/mathml-refresh/mathml/issues/6#issuecomment-532762535
We agreed during one meeting that we should go over the list of accent operators and removed unnecessary properties.

**Comment by NSoiffer** [comment]
In looking over the list, I saw one entry that _should_ be an accent that isn't currently:
```
&#x5E; | ^ | circumflex accent
```

**Comment by NSoiffer** [comment]
From #6, some operators listed as accents that should _not_ have the accent property.
```
 &#xAA; ª feminine ordinal
 &#x22; " quotation mark
 &#x201B; ‛ single high-reversed-9 quotation mark
```
If U+00AA is in the list, so should
```
&#xBA;   º   masculine ordinal indicator
```

**Comment by fred-wang** [comment]
I think ordinal indicators should just be removed, I don't think they correspond to any math operator: https://en.wikipedia.org/wiki/Ordinal_indicator

**Comment by NSoiffer** [comment]
I was wrong about 
```&#x5E; | ^ | circumflex accent```

It has both an infix and postfix version and the postfix version has `accent="true"`, while the infix versions does't. This is correct.

I'm not sure why I earlier said 
```
&#x22; " quotation mark
&#x201B; ‛ single high-reversed-9 quotation mark
```
should not have accent properties. People might potentially use them in an overscript position and when they do, they should be treated as accents.

I removed the ordinal indicators from xml-entities/unicode.xml

**Comment by NSoiffer** [comment]
Bizarrely (at least to me) the U+0080 block has B2, B3, and B9 as superscript 2, 3, and 1 (yes, in that order). I think these should be pulled from the Operator Dictionary because:
1. you shouldn't use them as superscripts (use `msup`)
2. they aren't a complete set, so not that useful
3. I can't imagine why software (i.e, a MathML generator) would ever want to use them.

Is there anyway to find out whether they are used inside of MathML?

**Comment by NSoiffer** [comment]
In looking at the arrows, we have a relatively consistent set of rules for when an arrow is an accent: any horizontal arrow is an accent and non-horizontal arrows are not.  It is of course always possible to add `accent="true"`, but if you used an arrow in an under/overscript, I think the odds are high you would want it to be small and away from the base.  I think we should add at least the diagonal forms of the arrows as I could imagine them being used as a limit. Since some arrows curve, that "diagonal" gets to be a bit subjective, so maybe all the arrows should have limits...

In looking through the operator dictionary, there are the diagonal arrows I found that probably should have `accent="true"` by default:
* the diagonal arrows x2196 - x2199
* x21AF;	↯	downwards zigzag arrow
* x21B8;	↸	north west arrow to long bar
* x21D6 -x21DA;	⇖	diagonal double arrows
* x21F1;	⇱	north west arrow to corner
* x21F2;	⇲	south east arrow to corner
* x2921 - x2932 various mostly diagonal arrows, some as crosses
* x2934 - x2937 some curved pointing arrows


The operator dictionary missed these horizontal arrows. For consistency, they should have `accent="true"`:
* x2956;	⥖	leftwards harpoon with barb down to bar
* x2957;	⥗	rightwards harpoon with barb down to bar
* x2B45;	⭅	leftwards quadruple arrow
* x2B46;	⭆	rightwards quadruple arrow

These have arrows below an operator and should _not_ be accents but are listed as having accents (they are some variants of operators):
* x2971 - x297D: these have arrows below an operator and shouldn't be accents
(as an example x2971;	⥱	equals sign above rightwards arrow)

**Comment by NSoiffer** [comment]
At the 13/1/20 meeting, @fred-wang proposed removing the `accent` property entirely from the operator dictionary. Instead, _all_ operators would default to having `accent="true"`. This was sparked by my suggestion for making all arrows have `accent="true"`. In a scan of the operator dictionary, I didn't see anything that would say that's a bad idea. _If anyone knows of a reason why it would be a bad idea, please add some examples._

A more radical suggestion would be to remove `accent` from `mo` altogether and leave that up to the `munder` etc, element attrs (with default being all `mo`s turning on accents). That has compatibility issues and any polyfill/transform would affect the DOM, so not ideal. People were disinclined to that suggestion.

**Comment by NSoiffer** [comment]
At the 20/1/20 meeting, we resolved to take accent out of the operator dictionary and change spec to say it is `default="true"`.

It has been removed from the operator dictionary.

**Comment by fred-wang** [comment]
This still need tests, will happen when the op dict tests are regenerated.
