### ISSUE TITLE
"initial" is not a legal specified value that can be checked

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#154]
In the [spec](https://mathml-refresh.github.io/mathml-core/#the-math-script-level-property), the scriptlevel mentions checking for `initial`. This is not legal according to the [CSS spec](https://www.w3.org/TR/css-cascade-3/#defaulting-keywords).

The currently says:

> If font-size is specified or if the specified value of math-script-level is initial then math-script-level does not affect the computed value of font-size.

The spec should check against 0, which is the initial value. The spec should probably say this.

**Comment by tabatkins** [comment]
Yes, the 'initial' keyword disappears by specified value time, via the defaulting process. <https://drafts.csswg.org/css-cascade/#specified>

They're technically visible at earlier stages, but those stages aren't exposed or manipulated by anything else; they're a spec fiction to help explain the process in detail.

So yeah, key off of the actual initial value, not the 'initial' keyword.

**Comment by fred-wang** [comment]
Checking against 0 won't cover the usual case where the user explicitly resets the scriptlevel to the font-size of the `<math>` root:

    <math>
      <mfrac>
        <mstyle scriptlevel="0">...</mstyle>
        <mrow>...</mrow>
      </mfrac>
    </math>

---------------------

In order to ensure that CSS math-script-level=0 corresponds to MathML3's scriptlevel="0", the UA sheet has the following rule:

    math {
        math-script-level: initial;
    }

and in order to prevent this rule from changing font-size (if math-script-level was set to a nonzero value in one ancestor) the math-script-level definition contains "the specified value of math-script-level is initial". I believe we were able to check and test this case in our Chromium implementation but maybe it was wrong and we shouldn't do that if that's not allowed by the CSS anyway.

So I see two options:

(1) Either remove both "math-script-level: initial" and "the specified value of math-script-level is initial". This means that if someone sets math-script-level to nonzero on an ancestor (e.g. with nested `<math>` tags) then we would have a mismatch between CSS/Core and MathML3's concept.

(2) Or keep "math-script-level: initial" and remove "the specified value of math-script-level is initial". This means that if someone sets math-script-level to nonzero on an ancestor (e.g. with nested `<math>` tags) then the font-size will be reset on the `<math>` tag.

**Comment by fred-wang** [comment]
(of course a third option would be to introduce a new keyword, but probably not worth it if at the end we do #174 )

**Comment by brucemiller** [comment]
Is there a notion of the font-size effective at the math element? If so, call it initial-font-size, then rather than saying that script-level=0 does not change the font size, it could say that it resets it to the initial-font-size.

**Comment by NSoiffer** [comment]
The intent of setting scriptlevel="0" is that the font size is reset to the initial value. That's what both Firefox and MathPlayer do... at least in the trivial test I tried:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mfrac>
    <mstyle scriptlevel="0">
      <mn>1</mn>
    </mstyle>
    <mn>2</mn>
  </mfrac>
</math>
```

**Comment by fred-wang** [comment]
> Is there a notion of the font-size effective at the math element? If so, call it initial-font-size, then rather than saying that script-level=0 does not change the font size, it could say that it resets it to the initial-font-size.

Yes, but CSS resolution of an element cannot directly involve the values of arbitrary ancestors, it just uses the one inherited from its the parent.

As Neil said, scriptlevel=0 is already supposed to move back to the initial size, except in edge cases when someone decides to modify the font-size inside the formula (e.g. using mathsize) or when the minsize had been reached due to too many nested expressions. 

My comment was about *nested* `<math>` tag, which I also consider an edge case. This was discussed in the CG meeting with Emilio.

**Comment by fred-wang** [comment]
Closing after the change in https://github.com/mathml-refresh/mathml/issues/174
