### ISSUE TITLE
Operator Dictionary: Remove "priority" from MathML Core

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#161]
" The 'Priority' column is significant for the proper grouping of sub-expressions using <mrow>. This is especially relevant to the automatic generation of MathML by conversion from other formats for displayed mathematics, such as TEX, which do not always specify how sub-expressions nest. However, it does not affect the rendering described in this specification and so is not needed for implementing it in user agents. "

I propose to remove this from core as it is basically useless for rendering in browsers and we likely don't want to specify native editing. Authors of tools should refer to MathML full instead.

Main rationale: This will allow to remove many entries from the operator dictionary, since they would just use the default values and hence make the operator less "frightening". I'll open a separate issue about this later.

**Comment by NSoiffer** [comment]
For something as large as the operator dictionary, there should be a master copy that is used in both specs. When you say "remove", hopefully you mean "filter out" the "priority" column via some software. 

If the main concern is making it less "frightening", then perhaps just graying out unused columns via CSS would be a better solution, with a comment at the top of the table saying grayed out columns do not apply to core.

**Comment by fred-wang** [comment]
> For something as large as the operator dictionary, there should be a master copy that is used in both specs. When you say "remove", hopefully you mean "filter out" the "priority" column via some software.

The official dictionary remains @davidcarlisle 's unicode.xml ; the idea is just to filter out what is really needed to implement MathML Core in browsers. priority is not used at all.

> If the main concern is making it less "frightening", then perhaps just graying out unused columns via CSS would be a better solution, with a comment at the top of the table saying grayed out columns do not apply to core.

Maybe we should have a separate spec with the operator dictionary formatted from unicode.xml so that users can have a convenient way to read it.

Currently the dictionary has ~1100 entries and was the largest file when we analyzed Chromium Android build with https://chromium.googlesource.com/chromium/src/+/HEAD/tools/binary_size/README.md#diagnose_bloat_py ;  just removing 379 entries (which use the default attribute values) already saved a lot of space. I'm sure we can optimize things even more since the dictionary has a lot of redundancy and unused data ( I did a quick experiment in https://github.com/mathml-refresh/mathml-core/commit/00e19bd1a477f789b3cc0f531cab79f7c75a9489 ). Although this is maybe just an implementation details, I feel it would be good to describe an optimized handling in the core spec for implementers. As I said I'll come back to this later when I have time.

**Comment by davidcarlisle** [comment]
I am moderately against having a separate spec, that is essentially what the xml-entities spec is now even though the text of the spec is notionally about the entity names , that is really just a lightly styled view of one part of the unicode-xml data there is very little source text other than that.

unicode.xml is used to generate other things as well notably the tool to show unicode code points used in a run of text

https://w3c.github.io/xml-entities/unicode-names.html

and also JSON files such as 

https://w3c.github.io/xml-entities/2007/htmlmathml.json

You mention that unicode.xml is a large file in the chromium android sources but really I think we should fix that by making a json or xml file that has the data needed for a browser source, there is a lot to be gained by tracking tex package names for characters in the same file, but not a lot to be gained by checking them in to a browser source tree, so I would suggest that as part of the entities spec build we build a separate file (in whatever format is useful) that is taken as source for implementations of mathml core.   Naturally this could drop anything without a non-default operator dictionary entry.. So perhaps all you need is a core specification of what needs to be in the operator dictionary, and then we extract a (xml? json?) file that just has that data, then make it available in the same way as the htmlmathml.json json file above.

**Comment by fred-wang** [comment]
> I am moderately against having a separate spec, that is essentially what the xml-entities spec is now even though the text of the spec is notionally about the entity names , that is really just a lightly styled view of one part of the unicode-xml data there is very little source text other than that.

Then why the operator dictionary table cannot be on that spec, since that's where the data belongs?

> You mention that unicode.xml is a large file in the chromium android sources

I never mentioned that unicode.xml is in any browser source, fortunately that's not the case :-)

What we have in the browser source is the current operator dictionary which is *already* big. My proposal is just to filter out and reorganize stuff in MathML Core so that it does not suggest to implementers to integrate this big 1100 entries, as that's currently the case. FWIW I plan to write the script to handle do that so you don't need to maintain anything else than unicode.xml. There wouldn't be any behavior change for native MathML support. For a "readable" table MathML Core would refer to xml-entities. And MathML4 could refer to xml-entity too instead of duplicating the table in its appendix.

**Comment by fred-wang** [comment]
For the record, this is the output of the script I mentioned above right now:


    ('entriesWithMultipleCharacters', 46)
    ('infixEntriesWithDefaultValues', 379)
    ('infixEntriesWithSpacing3', 85)
    ('infixEntriesWithSpacing4', 182)
    ('infixEntriesWithSpacing5AndAccent', 75)
    ('infixEntriesWithSpacing5AndAccentStretchy', 70)
    ('infixEntriesWithSpacing5AndStretchy', 68)
    ('otherEntries', 202)
      * 30: {'lspace': 0, 'rspace': 0, 'form': 'postfix', 'properties': {'accent': True}}
      * 25: {'lspace': 0, 'rspace': 0, 'form': 'prefix', 'properties': {'symmetric': True, 'stretchy': True, 'fence': True}}
      * 25: {'lspace': 1, 'rspace': 2, 'form': 'prefix', 'properties': {'symmetric': True, 'movablelimits': True, 'largeop': True}}
      * 25: {'lspace': 0, 'rspace': 0, 'form': 'postfix', 'properties': {'symmetric': True, 'stretchy': True, 'fence': True}}
      * 20: {'lspace': 0, 'rspace': 0, 'form': 'postfix', 'properties': {'accent': True, 'stretchy': True}}
      * 12: {'lspace': 1, 'rspace': 2, 'form': 'prefix', 'properties': {'symmetric': True, 'largeop': True}}
      * 10: {'lspace': 0, 'rspace': 1, 'form': 'prefix', 'properties': {'symmetric': True, 'largeop': True}}
      * 7: {'lspace': 2, 'rspace': 1, 'form': 'prefix'}
      * 6: {'lspace': 0, 'rspace': 0, 'form': 'infix'}
      * 5: {'lspace': 1, 'rspace': 1, 'form': 'infix'}
      * 5: {'lspace': 0, 'rspace': 1, 'form': 'prefix'}
      * 3: {'lspace': 0, 'rspace': 0, 'form': 'prefix'}
      * 3: {'lspace': 0, 'rspace': 0, 'form': 'postfix'}
      * 3: {'lspace': 0, 'rspace': 2, 'form': 'postfix'}
      * 2: {'lspace': 0, 'rspace': 0, 'form': 'postfix', 'properties': {'fence': True}}
      * 2: {'lspace': 4, 'rspace': 4, 'form': 'infix', 'properties': {'stretchy': True}}
      * 2: {'lspace': 0, 'rspace': 0, 'form': 'prefix', 'properties': {'fence': True}}
      * 2: {'lspace': 5, 'rspace': 5, 'form': 'prefix', 'properties': {'stretchy': True}}
      * 2: {'lspace': 0, 'rspace': 3, 'form': 'infix', 'properties': {'separator': True}}
      * 2: {'lspace': 1, 'rspace': 2, 'form': 'infix'}
      * 2: {'lspace': 1, 'rspace': 1, 'form': 'prefix'}
      * 2: {'lspace': 0, 'rspace': 0, 'form': 'prefix', 'properties': {'stretchy': True, 'fence': True}}
      * 2: {'lspace': 0, 'rspace': 0, 'form': 'postfix', 'properties': {'stretchy': True, 'fence': True}}
      * 1: {'lspace': 1, 'rspace': 0, 'form': 'postfix'}
      * 1: {'lspace': 2, 'rspace': 0, 'form': 'prefix'}
      * 1: {'lspace': 1, 'rspace': 1, 'form': 'prefix', 'properties': {'stretchy': True}}
      * 1: {'lspace': 0, 'rspace': 0, 'form': 'infix', 'properties': {'separator': True}}
      * 1: {'lspace': 2, 'rspace': 2, 'form': 'infix', 'properties': {'symmetric': True, 'stretchy': True, 'fence': True}}

**Comment by davidcarlisle** [comment]
> 
> 
> > I am moderately against having a separate spec, that is essentially what the xml-entities spec is now even though the text of the spec is notionally about the entity names , that is really just a lightly styled view of one part of the unicode-xml data there is very little source text other than that.
> 
> Then why the operator dictionary table cannot be on that spec, since that's where the data belongs?

The spec (rather than the underlying data) is just focussed on mapping names to characters, I'm not sure that math-specific rendering information fits. MathML  or mathml-core seem more suitable specs even if they  share the data 

As I say the words of the spec are mainly focussed on the extracted entity names, it does link to the full xml file, I always assumed any implementation of any part of that would come from data extracted from unicode.xml so having a "human readable" rendition in a spec doesn't help much, I doubt many humans have read that appendix of mathml3.
> 
> > You mention that unicode.xml is a large file in the chromium android sources
> 
> I never mentioned that unicode.xml is in any browser source, fortunately that's not the case :-)
> 

I did wonder:-)

> What we have in the browser source is the current operator dictionary which is _already_ big. My proposal is just to filter out and reorganize stuff in MathML Core so that it does not suggest to implementers to integrate this big 1100 entries, as that's currently the case. FWIW I plan to write the script to handle do that so you don't need to maintain anything else than unicode.xml. There wouldn't be any behavior change for native MathML support. For a "readable" table MathML Core would refer to xml-entities. And MathML4 could refer to xml-entity too instead of duplicating the table in its appendix.

Not duplicating is of course good. As you know this was all originally in the MathML spec before we split out the entity names (which then also got picked up by html).

wherever unicode.xml is, I'd agree that especially in core a far more compact presentation is possible, where you give a particular set of properties then just list the characters with that set, this would correspond to the usual tex documentation where you say the following characters are \mathrel:  =,<,... and just list them, you don't need to describe \mathrel spacing for each character.

That saving is I think easiest if you don't list priority, which woul dmake far more characters have the same properties.  I think there is a separate issue on dropping priority somewhere. Certainly in core I don't see any issue with that, I'm not totally convinced that priority is that useful in the full spec, it is at best a gentle hint to authoring systems to generate reasonable markup, it's not anything that can be used by a mathml system itself.

**Comment by fred-wang** [comment]
> The spec (rather than the underlying data) is just focussed on mapping names to characters, I'm not sure that math-specific rendering information fits. MathML or mathml-core seem more suitable specs even if they share the data
> 
> As I say the words of the spec are mainly focussed on the extracted entity names, it does link to the full xml file, I always assumed any implementation of any part of that would come from data extracted from unicode.xml so having a "human readable" rendition in a spec doesn't help much, I doubt many humans have read that appendix of mathml3.

OK, my proposal is dropping the "human readable" table from MathML Core. I don't really care whether we actually want can to keep it and where else to put it. But I suspect some in this group are still interested.

> That saving is I think easiest if you don't list priority, which woul dmake far more characters have the same properties. I think there is a separate issue on dropping priority somewhere. Certainly in core I don't see any issue with that, I'm not totally convinced that priority is that useful in the full spec, it is at best a gentle hint to authoring systems to generate reasonable markup, it's not anything that can be used by a mathml system itself.

This is #161 but again some people might find it useful, so we should find a place for it. I don't want it on MathML Core since it does not have any effect and is not testable.

**Comment by davidcarlisle** [comment]
I attach an html file (as .txt) with the more compact arrangement suggested above.  Currently it just shows the form and left and right space with other properties in a title attribute so will show on a tooltip (essentially arbitrary list of properties shown, currently accent and stretchy if true,  and priority and unicode name)

looking at it in that form it's clear the list would be much shorter if you assumed infix implied lspace=rspace=5  unless otherwise specified but also some of the other entries look rather odd why are the integrals like U+2A15 spaced differently to contour integrals such as U+222E? If we rationalise some of these spacing defaults there would be I suspect fewer groups and the table would compact even more.

Perhaps core should link to a normative machine readable table in json or whatever of the data it needs and full should show the table in something like this? Not necessarily this layout exactly I just made this in the last minute or so, although already I think it's more readable than the display we used at https://www.w3.org/TR/MathML3/appendixc.html#oper-dict.entries-table


[opdict.txt](https://github.com/mathml-refresh/mathml/files/3831674/opdict.txt)

**Comment by fred-wang** [comment]
> looking at it in that form it's clear the list would be much shorter if you assumed infix implied lspace=rspace=5 unless otherwise specified but also some of the other entries look rather odd why are the integrals like U+2A15 spaced differently to contour integrals such as U+222E? If we rationalise some of these spacing defaults there would be I suspect fewer groups and the table would compact even more.

I would avoid modifying too much the current values to avoid backward compatibility issues  (using default spacing for all infix operators sounds a big change) . However if some entries look odd or if they correspond to operators that are not really used in practice (like "down fish tail") I think we can try to remove them or align their values with similar operators.

**Comment by NSoiffer** [comment]
I like the shorter table format, although I don't really see the usefulness of having a compressed table be displayed in the spec. I think a link to an xml or json file would be best. Unicode does this for many (all?) of it's big tables such as canonicalization (they use CSV format with ";"s for the ones I've seen).

Another pass over the file is definitely in order. Right now, it is non-normative, so changes don't break anything. Once spacing and form are part of core, then they will become normative, so it would be good to carefully review this before that happens. It has been updated/changed several times so doing so in a move to MathML 4 should not surprise anyone. Big tables like this tend to have mistakes, especially since the values originally came from different existing implementations along with new entries from Unicode.

**Comment by fred-wang** [comment]
This is now done.
