### ISSUE TITLE
sAscent defined twice, sDescent not at all

### ISSUE THREAD

**Issue by faceless2** [w3c/mathml#196]
As the subject states - there's a typo in the spec in 3.3.1.1 item 4:

https://mathml-refresh.github.io/mathml-core/#algorithm-for-stretching-operators-along-the-block-axis

**Comment by fred-wang** [comment]
Yes, bad copy & paste. Should be Sascent = max(...) +  AxisHeight and Sdescent = max(...) -  AxisHeight.

**Comment by faceless2** [comment]
Quick edit before you close: next point, section 5:

> Otherwise, if maxsize < T then multiply Tascent, Tdescent by maxsize / T.

should be

Otherwise, if maxsize < T then multiply Tascent, Tdescent by T / maxsize .

**Comment by faceless2** [comment]
Sorry, but I don't think that's right either - I've just plugged that algorithm in with the following input and output
```
uAscent = 27, uDescent = 7, axisHeight = 4
sAscent = max(27 - 4, 7 + 4) + 4 = 27
sDescent = max(27 - 4, 7 + 4) - 4 = 19
```
so uAscent + uDescent = 34 but sAscent + sDescent = 46? Doesn't seem right.

Perhaps you meant `min` instead of `max`?
```
sDescent = min( Uascent − AxisHeight, Udescent + AxisHeight ) - AxisHeight
```
which seems to give the right result - I presume the intention is to center on the mathematical baseline, like so:
```
sAscent = (uAscent + uDescent) / 2 + axisHeight
sDescent = (uAscent + uDescent) / 2 - axisHeight
```

**Comment by fred-wang** [comment]
@faceless2 the intention is to follow what MathML 3 says: stretch symmetrically with respect to the math axis.

**Comment by fred-wang** [comment]
This is the blue case in figure 11

**Comment by faceless2** [comment]
I can confirm it should be "min" not "max" for sDescent in that case - we've swapped in the line in my comment above to the algorithm, and it works properly

**Comment by fred-wang** [comment]
Sorry, I was about to go out when I replied. Here is the explanation:

* Uascent and Udescent are the parts of non-stretchy siblings above and below the baseline. **These are the target metrics used for non-symmetric stretching**
* Uascent - AxisHeight and Udescent + AxisHeight are the parts of non-stretchy siblings above and below the math axis.
* When stretching symmetrically with respect to the math axis, you want to use the same values above and below the math axis. However, in order to cover the non-stretchy siblings you still want the value above to be at least Uascent - AxisHeight and the value below to be at least Udescent + AxisHeight, so the minimum value you can pick for that purpose is the max between these two values. 
* Sascent and Sdescent are symmetric target size above and below the baseline. You obtain them from the maximum of the previous point by adding / substracting AxisHeight.  **These are the target metrics used for symmetric stretching**

With your proposal, uAscent = 27, uDescent = 7, axisHeight = 4

max(27 - 4, 7 + 4) + 4 = 27
min(27 - 4, 7 + 4) - 4 = 7

27 - 4 != 7 + 4 is not longer symmetric, actually you said "it works properly" because these are just Uascent and Udescent i.e. the non-symmetric stretching! 

If you switch uAscent and uDescent, you still get

max(7 - 4, 27 + 4) + 4 = 27
min(7 - 4, 27 + 4) - 4 = 7

This is still not symmetric and even worse, sDescent == 7 does not cover uDescent == 27. 

With the definition in the spec, you get:
sAscent = max(27 - 4, 7 + 4) + 4 = 27
sDescent = max(27 - 4, 7 + 4) - 4 = 19

So you have:
- Symmetry: sAscent - 4 == sDescent + 4 == 23
- Covering target: sAscent == 27 >= uAscent == 27, sDescent == 19 >= uDescent == 7
- But sAscent + sDescent != uAscent + uDescent. This is on purpose!
 
Hope that helps.
