### ISSUE TITLE
What attribute wins when we have both display and displaystyle on math

### ISSUE THREAD

**Issue by rwlbuis** [w3c/mathml#203]
What attribute wins when we have both display and displaystyle on math? Both will map internally to math-style.

**Comment by rwlbuis** [comment]
In firefox displaystyle seems to win.

**Comment by fred-wang** [comment]
I think displaystyle should win because display specify both centering/block + math-style while displaystyle allows to refine the math-style. 

Currently, the spec says the math-style for math@display is implemented in the UA sheet: https://mathml-refresh.github.io/mathml-core/#user-agent-stylesheet while displaystyle is mapped to math-style (in the code). So I guess the latter is stronger than the former.

**Comment by fred-wang** [comment]
I think there are some tests mixing display and displaystyle.

**Comment by fred-wang** [comment]
@rwlbuis This is tested by https://w3c-test.org/mathml/relations/css-styling/displaystyle-1.html (and even https://w3c-test.org/mathml/relations/css-styling/displaystyle-015.html)

Closing since this is a particular case of issue #215 : 

displaystyle attribute is author-level zero-specificity
display attribute is implemented with UA sheet rules

so displaystyle wins over display.
