### ISSUE TITLE
Bug in mrow layout wrt to lspace/rspace

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#205]
The core spec gives a [layout algorithm for mrow](https://mathml-refresh.github.io/mathml-core/#layout-of-mrow) that mostly gets lspace/rspace right, but in some cases adds lspace/rspace inappropriately at the start/end of an mrow (could be an implied mrow). The problem occurs when the mrow is the only element of an mfrac, in scripts, in table cells, and a few other cases and there is an mo at the start/end of the mrow with a non-zero lspace/rspace. This is because lspace/rspace is added to the first/last element of the mrow in these cases and it should not be added. Here is a [codepen](https://codepen.io/nms/pen/GRJemag) that if viewed in Firefox, shows the correct behavior.

With the current core spec algorithm, the third fraction will be wider than the other two fractions because the spacing around the '=' will be part of the denominator, which is not desirable/wrong.

Note: setting `add-space` to false at the start of the algorithm would fix this problem but would then break spacing when there are nested mrows that start/end with an mo.

Although the example is contrived (so that the problem is obvious), in real life this effects something like dy/dx, where the differential d is a prefix operator that has lspace>0. It has this to avoid the problem that TeX has where a thin space needs to be manually added in front of it in integrals to get the spacing to look ok.

Note: MathPlayer has a nice tweak to its layout algorithm that changes the simplistic 'the space between two tokens is rspace+lspace' to be max(rspace, lspace). This makes a notation like dy = dx have symmetric spacing around the '=' as opposed to it having extra space after the '=' due to the lspace of the 'dx'. I think it would be good to add that to a revised algorithm. With the current one, doing this appears to be hard.

**Comment by fred-wang** [comment]
First I'd recommend to use `<mo lspace="3em" rspace="3em">=</mo>` to make the bug more obvious. Second, "implied mrow" is a MathML3 concept, there is not such a definition in MathML Core. Third just to clarify the layout algorithm is recursive, starting from the math root.

In your example, the math will be laid out according to [mrow], which starts with [vertical-stretching] which

1. lays out all the non-embellished children:
   1. mn children with [mtext]
   2. third mfrac with [mfrac] which lays out 
       1. numerator with [mo] which adds no space.
       2. denominator with [mtext]
2. calculate the U and S ascent/descent from these.
3. lays out the embellished children with the stretch constraint U ascent/descent.
   1. first mfrac with [mfrac] which lays out
       1. numerator with [mo] which adds no space
       2. denominator with [mtext]
   2. second mfrac with [mfrac] which lays out
       1. numerator with [mtext]
       2. denominator with [mo] which adds no space
4. set add-space to true (because it's a math tag, but actually not even an embellished op) and so adds space around the first (lspace=rspace=0) and second (default spacing for =) mfrac elements only. The mn and third mfrac element gets no space around it.  

Now if you modify the mfrac elements to wrap its elements into an explicit mrow, then the first and second mfrac remains embellished operators and the third one remains a non-embellished operator, so the general structure remains the same. The difference is in the layout of 1.ii.a, 3.i.a and 3.ii.b which are now using [mrow]. But these are mrow with a single mo, so add_space = false and it's the same as the layout of the mo alone.

This is how it is done in Chromium, which implements this algorithm.

[mrow] https://mathml-refresh.github.io/mathml-core/#layout-of-mrow and so add-space=true
[vertical-stretching] https://mathml-refresh.github.io/mathml-core/#dfn-algorithm-for-stretching-operators-along-the-block-axis
[mtext] https://mathml-refresh.github.io/mathml-core/#layout-of-mtext
[mfrac] https://mathml-refresh.github.io/mathml-core/#fractions-mfrac
[mo] https://mathml-refresh.github.io/mathml-core/#layout-of-operators
