### ISSUE TITLE
content mathml in csymbol

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#276]
Chapter 5 says

https://w3c.github.io/mathml/#mixing_pmincm

> **Presentation markup within the csymbol element.**
>
> The csymbol element may contain either MathML characters interspersed with presentation markup, or content markup. It is a MathML error for a csymbol element to contain both presentation and content elements. 

This is copied from MathML3 but appears to be in error, I don't think any version of MathML has allowed Content in csymbol.  The syntax table in the csymbol section, the MathML3 schema and the draft MathML4 schema all have csymbol having the same content model as other content token elements such as ci. (text, mglyph or presentation mathml)

**Comment by NSoiffer** [comment]
I agree. I don't know of a use case for content in `csymbol`. Does anyone?

**Comment by brucemiller** [comment]
Indeed, that seems to have been present already in MathML 2. But the 
description of csymbol in Chapter 4 (in both MathML 2 and 3) restrict it 
to presentation markup only.  I can't think of a reason to nest content 
within csymbol; anything with "meaning" presumably should have appeared 
as an argument that the csymbol is applied to, rather than embedded 
inside it.
