### ISSUE TITLE
math in math

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#347]
The example at 

https://w3c.github.io/mathml/#examples-7

starts

```
 <math display='block'>
 <mrow data-changed='added'>
```

This is the only example that has `<math` and the mathml-inlining code always wraps a `<math display="block">` around the example so we get math in math here (and fail pubrules checks).

I could simply delete but @NSoiffer  do you think the `display=block` is important for the context here (since the example is about displaystyle)? It would be possible to invent a new css class to prevent math being added or to do some regex search for  `<math`  before adding another, but as this is the only example, if we can just delete the `<math>` that would be simpler:-)

The second line has a `data-changed` attribute which may have been part of the MathML3 diff marking, I don't remember, but here it's just appearing in the output, so I think it can go?

**Comment by NSoiffer** [comment]
Sorry -- I thought I deleted the `data-changed` (which comes from MathCAT's canonicalization). The display-block is important in the sense that the top-level `mfrac` will display wrong without it.  However, since you wrap `<math display="block">` around it and this is obviously not meant to be inlined, I think removing `math` is fine. I'll do that.
