### ISSUE TITLE
intent grammar -- should allow '.12' as a number

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#376]
Currently, the spec says
```
number   := '-'? digit+ ('.' digit+)? 
```

But this does not allow a leading decimal point. For example:  `.1`. That seems like a mistake.

I suggest:
```
number  := '-'? (digit+ '.'? digit* | '.' digit+)
```
Or to just modify what we already have:
```
number  := '-'? (digit+ ('.' digit+) | '.' digit+)
```
But some regex handlers (such as Rust's) don't support nested parens (it's a speed reason), so I think the first form is a better one to use in the spec.

**Comment by dginev** [comment]
This is already possible by using `0.1` and `0.12`.

If we appear to have enough energy for extending the grammar for numeric literals, I think I will have to re-open my plea for motivating examples for each class of additional syntactic coverage and its benefits to AT. Starting with the negative numbers, since we skipped over them rather quickly.

When would we need `.1` marked up explicitly as `intent=".1"` ? Couldn't we just assume it will already be instantiated via an `<mn>.1</mn>` that would need no further annotation? Having explanations for this would also help intent adopters down the line.

**Comment by NSoiffer** [comment]
Off the top of my head, I don't have an example that involves numbers in any way. But if we are going to allow numbers, we shouldn't restrict them. Going to an extreme using your argument: I can't think of a reason to allow all of NCNAME. In particular, I can't give you an example that starts with "zz" or a Roman letter followed by a Greek one, so why are we allowing them? I realize you said "syntactic class", but is ".12" and "0.12" really different syntactic classes? It is just capturing what is typically used with we talk about numbers with decimal points.

**Comment by dginev** [comment]
> I can't think of a reason to allow all of NCNAME. [...]  so why are we allowing them?

I was told in our meeting last Thursday that NCName was the only "politically viable" design choice that does not enter a very painful discussion of what exactly a "letter" is/ought to be for `intent`. My initial personal preference was for having a more restricted `name` than NCName, which only relies on a Unicode-friendly category of "letters" and the "-" separator. It still is, if it ever becomes "politically viable".

> Off the top of my head, I don't have an example that involves numbers in any way.

Right - that is my concern - neither do I. Early on it seemed sensible to allow some basic numeric literals for "exceptional cases" where one may want to write them inside an intent expression. Though I can't come up with a great example at the moment.

Edit: After some digging, I found a good [lecture snippet](https://youtu.be/XoTeTHSQSMU?t=569) that introduces explicitly the "mover with bar" notation for negative numbers, and uses them in introducing finite fields. So the minimal MathML example which follows from that would be:
```xml
<mover intent="-3">
  <mn>3</mn>
  <mo>¯</mo>
</mover>
```

Edit 2: As I kept listening to that lecture, I reached an instance of that bar operation [used on an identifier](https://youtu.be/XoTeTHSQSMU?t=1701) `b`. In the intent values, this would be likely useful as:
```xml
<mover intent="negative($b)">
  <mi arg="b">b</mi>
  <mo>¯</mo>
</mover>
```

And the question becomes then, what is really gained by introducing the literal `-` number literals to the grammar, if we still have to use a named [negation](https://en.wikipedia.org/wiki/Negative_number#Negation) entry for identifiers. `-3` is briefer than `negative(3)`, but it adds two separate mechanisms for the same effect, which implementers will then have to support. 

---

When it comes to numeric literals, going for what is "typically used" enters deep waters pretty quickly as well:
 * complex numbers require `+` and `i` for e.g. the literal number `-1+3i`
 * numeric bases >10 customarily require letters, as in the hex number `DEADBEEF` (among other notable [magic debug hex values](https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_debug_values))
 * the decimal representation of irrational numbers can typically end with an ellipsis, as for example pi could be abbreviated as `3.14159...` Most irrational numbers don't have official names, so this can't be solved with using intent names. 
 * recurring decimals in the rationals can be written similarly, say `0.33333...`, but there are [multiple notations](https://en.wikipedia.org/wiki/Repeating_decimal#Notation): using parentheses `0.(3)`, viniculum/mover with bar, mover with dot, mover with arc. See the wiki link for the renderings.
 * questions about typicality of using dot `.` as a decimal separator are also tricky, given that there seem to be about [80 countries](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) that still prefer the decimal comma in technical writing, including my own (Bulgaria). It is fine to use the dot, since we can rely on precedent set by calculators and programming languages, but the "typical" argument is less universal than it may initially seem.
 * We haven't paid any mind to the Unicode additions that include non-traditional numeric literals, such as ¾ or ½. With the current setup, one possible recommendation would be to use `intent="0.75"` and `intent="0.5"`. Is this an upgrade for AT?
 * Another typical way of writing `.1`, besides `0.1`, is in e-notation, namely `1e-1`.
 * IEEE 754 uses a [signed zero](https://en.wikipedia.org/wiki/Signed_zero), which motivates `-0` and `+0` to be available as literals.
 
I'm sure I am missing at least another handful of questions related to numeric literals (Roman numerals, ...), but this should illustrate why I am already concerned of the growing complexity of the intent grammar in the numeric arena. It would be great to have some well-justified reasons about which numeric literal annotations are needed, when, and when not.

**Comment by davidcarlisle** [comment]
Ah, I had on my list of things I intended to get round to was replacing that informal definition of "number" by a link to "number"  in

https://w3c.github.io/mathml/#syntax-notation-used-in-the-mathml-specification

Currently only [unsigned number](https://w3c.github.io/mathml/#type_unsigned-number) is a `<dfn>` anchor as respec complains if you make a dfn that is not referenced., but clearly we could make number a dfn anchor and then reference it here. This would ultimately out-source the number syntax to CSS (and would meet @NSoiffer 's request to allow leading `.` )

**Comment by davidcarlisle** [comment]
@dginev  I don't think allowing or not allowing a leading `.` is "growing complexity of the intent grammar" whichever way we decide to go, it's just editorial pinning down of details.

The list  of issues you raise I don't think are problems in practice. 

Many (most?) programing languages manage wihout having literal complex and without allowing ¾.  The main use for numeric literals in intent is to supply numbers that are _not_ in the presentation so 1 and 2 are going to  be the main examples `sqrt` as `root($x,2)` or whatever.  If you can not express a literal approximation of an irrational number  that does not appear in the presentation, but is needed in the intent, then I don't think that that is a serious loss of functionality,

**Comment by NSoiffer** [comment]
For the record #376 contains an example where someone might use `.9` or `0.9` or any other value.

**Comment by davidcarlisle** [comment]
MathML3 chapter2 syntax table

https://www.w3.org/TR/MathML3/chapter2.html#id.2.1.5.1

defined `unsigned-number` to be a string of digits and at most one `.` and defined  `number` to be an unsigned-number optionally preceded by `-`

As a general rule the aim for MathML4 was to as far as possible align with existing web platform definitions, and with Core rather than have custom type definitions.

So in the main branch MathML4 version

https://w3c.github.io/mathml/#syntax-notation-used-in-the-mathml-specification

`unsigned-number` uses the CSS3 definition of `number`  but forbids a leading `-` or `+` This is used in several places including mpadded length attributes

`number` is just used in `scripsizemultiplier`  Unfortunately the chapter 2 table shows it is not used as it is using original markup, not respec `<dfn>` (The same is true for `color`)
It still has its original MathML3 definition of `unsigned-number` with optional precding `-` Bu now it is allowing CSS numbers with `e`  but as it doesn't allow `+`  it isn't the same as the CSS3 defined `number` type.

The current situation is a bit odd, it would be more natural to define `number` from CSS then define `unsigned-number` as a restriction of that with no leading sign.

For the new use in `intent` where CSS compaibility is a distraction,  I think I want to suggest a plan b

* Fix the syntax terms to consistently use `<dfn>` and respec references, so chapter 2 records where they are used.  Delete all really unused syntax terms from the table in chaper 2. (these do no have a bold link entry in the first column, if you click on a bold entry such as `unsigned-number` a pop up shows you where it is used). 
* in chapter 5 rename the terminal to `NumericLiteral` or some such so as not to clash with CSS `number`  and define it as some bnf for a string of digits with optional leading - and at most one `.`


That is, I don't think we should have two definitions of `number` but rather than make intent reference chapter 2 as in the open PR, we could rename it not to be called `number`, these names are just for internal spec consistency they don't affect the actual definittions.

**Comment by davidcarlisle** [comment]
looking at the discussion here and in #378 and #380, I suggest **not** merging the PR #377 and instead using

```
intent   := numlit | NCName | argref | funcall
funcall  := intent '(' [ intent [ ',' intent ]* ]? ')'
numlit   := '-'? (digit+ '.'? digit* | '.' digit+)
argref   := '$' NCName
```

That is

*  use the number form @NSoiffer suggested above.
* allow recursive `intent` as the head of `funcall` (renamed from`function`) (could disallow numbers but simpler to allow anything in the grammar and semantically `1(x)` no worse than `$foo(x)` where `$foo`  resolves to `1` )
* Allow empy argument list in `funcall`
* Keep the local definition of `numlit` (renamed from`number`) rather than reference chapter2 CSS `number`

**Comment by NSoiffer** [comment]
I'm good with what that grammar because:
* I don't think we should be restrictive in the floating point number -- being universal seems more compatible
* I've convinced myself that complicated heads for functions makes sense (see #380) and one shouldn't need to add an `mrow` to make that possible.

I'm not convinced that empty function args are needed. Despite what @davidcarlisle says, the new grammar does _not_ allow zero args.

**Comment by davidcarlisle** [comment]
> I don't think we should be restrictive in the floating point number -- being universal seems more compatible

@NSoiffer  er, yes alhough the least restrictive version of number would be as in the open draft PR that references CSS number syntax so also allows `+1e4`  . This doesn't go that far.

 > Despite what @davidcarlisle says, the new grammar does not allow zero args.

It does, unless I messed up. There is an extra `[..]?`  making all the content between `'('` and `')'`optional.

**Comment by NSoiffer** [comment]
>>    Despite what @davidcarlisle says, the new grammar does not allow zero args.

> It does, unless I messed up. There is an extra [..]? making all the content between '(' and ')'optional.

I missed the extra brackets. I'll blame that on my old pair of glasses I'm using while my new pair is being made ;-) I still don't think that's needed, but (unlike @dginev), I don't see the harm since it is minimal complexity to implement.

**Comment by dginev** [comment]
> > > Despite what @davidcarlisle says, the new grammar does not allow zero args.
>
> I still don't think that's needed, but (unlike @dginev), I don't see the harm 

Looks like some threads are getting mixed? Here is [my main comment](https://github.com/w3c/mathml/issues/378#issuecomment-1146199331) on the subject of empty arguments.

That is not a statement about harm, but a request to flesh out the need behind the additional syntax, so as to make adoption clear-cut.


---

As to this issue (decimals), David's latest grammar offer has made a traditional syntax for repeating decimals grammatical - such as the number `.54(3)`, traditionally meaning `0.54333...` - but with an unexpected parse, where we represent the application "0.54 of 3". That strikes me as unfortunate.

**Comment by brucemiller** [comment]
> I still don't think that's needed ... I don't see the harm 
I also can't quite see how the distinction between f and f() would be 
important to accessibility (but I don't have the experience.  But it's a 
critical distinction for computation.

The harm, perhaps, would be that allowing empty args would encourage 
people to think of intent as addressing computation rather than 
accessibility.

**Comment by davidcarlisle** [comment]
@dginev 

>  .54(3), traditionally meaning 0.54333...

Oh not syntax that I have seen before (not that me knowing a notation should  be a deciding factor)

We could change the head term from `intent` to `(NCName | argref | funcall)` if that will smooth acceptance?

**Comment by NSoiffer** [comment]
I had noticed that but thought that somewhere some researcher used number(args) to mean something, so why prevent. I hadn't considered it for repeating decimals, but there you go -- you learn something new everyday.

The problem is what AT should say. "point 5 4 of 3" is almost certainly wrong.  What should be said for "1(3)" and "1(x)", etc. So maybe the safe thing to do is to switch the grammar as @davidcarlisle suggests.

**Comment by brucemiller** [comment]
I believe expressions like 5(3) can mean a variety of different things
(repeated decimals; error bounds, likely others).
What AT should say in those cases is exactly what intent is for :>

We should not accept those expressions in the core intent syntax as if 
we know what they mean.

**Comment by davidcarlisle** [comment]
```
intent   := numlit | NCName | argref | funcall
funcall  := (NCName | argref | funcall) '(' ( intent (',' intent )* )? ')'
numlit   := '-'? (digit+ '.'? digit* | '.' digit+)
argref   := '$' NCName
```

**Comment by brucemiller** [comment]
Works for me...

**Comment by NSoiffer** [comment]
At the June 9 meeting, we agreed to #378 and #380. The number issue remains open and the committee left it @dginev and myself to resolve. When Deyan gets back from vacation, we should tackle this.

**Comment by NSoiffer** [comment]
This maybe should be a separate topic, but since it is part of this thread...

I had earlier agreed that we should drop numbers from the head because I had no idea what AT should do with them:
> The problem is what AT should say. "point 5 4 of 3" is almost certainly wrong. What should be said for "1(3)" and "1(x)", etc. So maybe the safe thing to do is to switch the grammar as @davidcarlisle suggests.

However, I just realized something that @brucemiller mentioned for complicated function "names" (e.g, `f(x)(y)`): one can get the number to be a function head via an `argref`: `$num(x)` where the matching element has `intent="3"`. I'm just about done implementing the grammar in #389, but I'm no longer a fan of it because there is extra complexity that in the end doesn't make producing speech any simpler. In fact, it probably makes it more likely the case of a number head/function name is not handled at all because recognizing it can occur is more obscure.

**Comment by dginev** [comment]
I agree with the example, but wonder about the conclusion. Who would write this and why? Are you worried about edge cases when people write erroneous annotations?

The latest intent grammar to some extent *discourages* using numbers as function heads, by defining 
```
function    := name | reference | application
```

Where the only reason we employ reference is to allow fine-grained annotations to an embellished head, as in:
```xml
<mrow intent="$function($x)">
  <msub arg="function" intent="index($f,$script)">
    <mi arg="f">F</mi>
    <mi arg="script">i</mi>
  </msub>
  <mo>(</mo>
  <mi arg="x">y</mi>
  <mo>)</mo>
</mrow>
```

which otherwise would only be possible as:
```xml
<mrow intent="index($f,$script)($x)">
  <msub>
    <mi arg="f">F</mi>
    <mi arg="script">i</mi>
  </msub>
  <mo>(</mo>
  <mi arg="x">y</mi>
  <mo>)</mo>
</mrow>
```

My personal bias has been to question whether we need number literals at all in the grammar, but one could also wonder if we want to allow references in function heads, now that we have introduced syntax allowing multiple applications in the same intent value.

**Comment by brucemiller** [comment]
@NSoiffer You don't need complicated function names to get a number as function head; just references. When you say you're no-longer a fan, surely you're not suggesting that a function head be restricted to an `NCName`?

I believe there should be a principle here, like with Content MathML, that it should be rich enough to express even incorrect mathematics.

**Comment by NSoiffer** [comment]
I meant that I'm no longer a fan of the changed grammar. I "believe" in allowing complicated function heads because it was easy to come up with two case [D^2 x and  (f ∘ g)(x) ] off the top of my head.

What I'm not a fan of is having both "function" and "application". I'd rather just have (I might have this wrong):
```
application := intent '(' arguments? ')'
```
because in the end, this describes the same potential result AT has to deal with as the current grammar (as of yesterday?)
```
application := function '(' arguments? ')'
function    := name | reference | application
```

**Comment by davidcarlisle** [comment]
I'd be happy to revert to allowing `intent` as the head of `application`, it makes it simpler to document as there are fewer terms to describe and as you say, restricting the head doesn't really prevent weird cases: just forces them to be obscured with indirect references.

Not totally related, but I was reminded of it while looking what could be in the head with or without that change. We no longer allow empty strings, which I'm not sure was ever explicitly decided. Probably they went when I switched the `name` production to use NCName. We could add them back in various ways but if we do, we would probably want to not allow them in the head of `application` as `intent=""` is possibly useful but `intent="(())((),,,,)` is rather weird.  

As we are aiming for intent mainly to help speech not computation I (now) think we should keep the grammar not allowing  empty, and then if it proves needed add something like `no-value` as a core intent value for a defined and pronouncable token for an empty argument, so `intent="no-value"` or even `intent="no-value(no-value())(no-value(),no-value,no-value,no-value,no-value)`

**Comment by dginev** [comment]
You may recall that I [pointed out](https://github.com/w3c/mathml/issues/376#issuecomment-1147705782) that allowing numeric heads for the applications clashes with a repeated decimal notation. I think we had some agreement that is too misleading, also in the June 9th group meeting.

I can only get behind Neil's proposed simpler rule of
```
application := intent '(' arguments? ')'
```

If literal numbers are no longer allowed in intent *at all*. Otherwise, either the grammar grows too large as to restrict certain categories of use, or we start allowing a variety of unintended expressions that can mislead remediators, rather than help them in some material way.

At the moment I am personally OK with removing literal numbers, going back to fewer and simpler rules, and postponing further extensions until MathML 5.

Otherwise, the current state of the grammar appears to be a good compromise.

**Comment by davidcarlisle** [comment]
It doesn't really _clash_ with that notation any more than it clashes with the far more common notations for implicit multiplications or array indexing:

 1(2)  same as a(b) or 3(x)  could have various interpretations if seen out of context but as you know the context is an expression matching the intent grammar there is no ambiguity. Looking at 3(x) you would guess it meant 3 times x, but the intent is intended to be read primarily by software not people and it has an unambiguous parse as a function 3 applied to x (which may well be meaningless but that isn't an issue at this level)

**Comment by brucemiller** [comment]
"1(2)" as a mathematical notation could have several interpretations, but as an intent value can *only* mean "1 applied to 2". However you want to speak it, it sounds weird, because it *is* weird; I don't know how to compute it, but don't need to; but it is what it is.

Having certain features in intent, such as nesting & references which (to me) feel mandatory, inevitably allows nonsensical things.  If I can write "Fourier transform of sin applied to x", then I can also write "sin of x applied to Fourier transform". As @NSoiffer pointed out, excluding literal numbers from function head, you can still get one via a reference.  For exactly the same reason, even excluding literal numbers completely doesn't solve anything.

We could develop a type system to flag these nonsensical constructs, but I'd suggest deferring that until MathML 7 or 8.

**Comment by davidcarlisle** [comment]
@dginev  thanks for the PR, it is good to have explicit code, even when it is, as you note, expressing a minority opinion.

It seems the group can't have a unanimously agreed proposal but consensus appears to be to allow intent recursively as the head of application.  I can't be on the call tomorrow, but that would be my vote and I suggest we leave any change until after the call.

I think it makes the intent grammar simpler to describe and simpler to use as you don't have to document the restriction.  I read your comment about reducing friction but honestly I just don't understand the issue and why  you think $a($b) is OK and 1(2) is not, neither is undersandable out of context. Both are expressions requiring a specific interpretation as specified in the spec.

**Comment by NSoiffer** [comment]
Agreed at meeting on July 12 that this can be closed with a required leading/trailing 0. 

I don't think the use of floating point numbers in `intent` is likely to happen and so not worth continuing a discussion on. So the grammar in the spec stands as is.
