### ISSUE TITLE
Intent: function requires arguments intentional?

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#378]
The intent grammar requires that the `function`s have arguments. Functions of no arguments are mathematically possible, but I'm not sure they are needed because the speech could be given as a literal on the function name. Nonetheless, I am raising this issue just to make sure that everyone agrees that the current grammar that doesn't allow zero-argument functions is intended.

**Comment by dginev** [comment]
> Functions of no arguments are mathematically possible

I am not sure this is true? It is not the case in the definition of a function as "a binary relation that is univalent and total". The only way I could mathematically see this as possible is if the empty argument list abbreviated the empty set, so `f()` really stood for `f(∅)`.

It is of course programmatically possible (even extremely common) to invoke functions with an empty argument list. But the word "function" no longer has the mathematical definition. It comes closer to "a named section of a program that performs a specific task".

Depending on your programming language that empty call `f()` can be a standing for an uninhabitable type or an actual empty list. Implementation details vary somewhat wildly between prog languages.

In any case, we'd need an example where such an intent value would be useful for AT. To me it seems a bit artificial, as we are not trying to attach any "executable" behavior, where a use of `f()` seems to make the most sense.

**Comment by NSoiffer** [comment]
Since someone might be exporting a Mathematica or Maple notebook to a web page where the expressions and function definitions are part of the notebook, it is certainly possible that someone has a function with no arguments defined. If the function had optional arguments, it _might_ be the case that they want a screen reader to speak the default values (which might be `.9` ;-) or maybe not. If not, the screen reader needs to indicate this is a function. That means the default speech rule for intent ('f of ...') needs a special case ('f of no arguments' or 'function f'). Or maybe (because some screen readers don't handle this well -- I left off this case in MathCAT but will add it now), someone wants to override the speech for `f()`. So that is a use case.

As I originally noted, they could do this by specifying the intent is a literal, so I don't think allowing an empty arg list adds functionality. The point of this issue is to raise awareness and make sure everyone realizes this notation is not permitted and agrees that is ok.

**Comment by brucemiller** [comment]
Oh! I initially misunderstood the Issue; see the aside.

@dginev is probably right that this is really more of a progamming question than pure math representation. However, although we required at least 1 argument in our earlier proposal, it probably more laziness than intentional on my part.  It's easily fixed with:
```
function := (NCName | argref) '(' [ intent [ ',' intent ]* ]?  ')'
```
But I'd also be curious how the distinction between `f` and `f()` might affect AT.

Aside: I think that the name of the production "function" is a bit off: it's really function-call or (function application, invocation or ...).

**Comment by davidcarlisle** [comment]
yes I think we should allow the no-argument form (and I nearly called the production `funcall` rather than `function`which might have been better

**Comment by dginev** [comment]
We would really benefit from a fully fleshed out example here, as will adopters.

Functions in the programming sense are called with empty arguments all the time. But those typically end up in (somewhat non-standard) `<pre>` or `<code>` blocks in HTML, rather than in MathML markup. The most standard concrete example I can think of is drawing pseudo-random numbers via  an empty call to a `rand()` function. 

In Mathematica's case, something like `RandomReal[]` [docs here](https://reference.wolfram.com/language/ref/RandomReal.html).

*If* a construct of this nature was to be written down in MathML, then am I understanding Neil that he would prefer markup akin to:

```xml
<mrow intent="RandomReal()">
  <mi>RandomReal</mi>
  <mo>[</mo>
  <mo>]</mo>
</mrow>
```

where we standardize the empty call for AT, and tools won't have to bother recognizing calls with different fencing, as in `f[]`, `f{}`, `f()`, etc. And if not, what concrete MathML snippet gets us closer to the intended use of the empty argument syntax?

Aside 1: notice the need of an extra mrow to hold this annotation.
Aside 2: there is an interesting question if we want to recommend standardizing casing, so that `intent="random-real()"` is preferred for this case, as to be compatible with the "Intent Open" list.

**Comment by dginev** [comment]
Another concrete question about edge cases that could be related here is "silence" or said differently - "ignoring nodes". Do we want a special value that explicitly "mutes" a MathML subtree, for the purposes of AT? The simplest suggestion would be the empty string, as in `intent=""`.

With a "silence" trigger, there can be an alternative to the vertical approach of wrapping a new `<mrow>` around any tree which needs intent annotation, where one can use a horizontal approach over the existing nodes. Namely:
```
  <mi intent="RandomReal()">RandomReal</mi>
  <mo intent="">[</mo>
  <mo intent="">]</mo>
```

without extra wrapping.

The benefit is that this type of technique could be useful in very long horizontal baseline expressions where the additional scaffolding `<mrow>`s could be seen as "too heavy". 

Yet, from a certain perspective this "silence"-based method is structurally worse. In either case, we should be aware that we are imposing restrictions on what Presentation trees are compatible with the new intent mechanism. This is likely veering too far off-topic for the current issue, but seems connected to fleshing out enough concrete examples so as to spot where unmet needs remain.

**Comment by NSoiffer** [comment]
I've thought about this some more and, for the record, I'm still ambivalent about it -- I don't think there is a good use case for it (the few edge cases that might occur seem like they can always be hacked around), but I don't see a strong case for excluding it as allowing it seems pretty trivial.

**Comment by brucemiller** [comment]
A lot have comments have criss-crossed the issues; there's a revised grammar in #376 that allows `f()`.  I'm OK with that.  I'm not so insistent that empty arguments be allowed, nor all that much against it either. It's hard to imagine an accessibility example that requires it (but easy to imagine a computational example that does).

**Comment by davidcarlisle** [comment]
a2a141d   allows empty list, so this can probably be closed

**Comment by NSoiffer** [comment]
Agreed as per today's MathML meeting
