### ISSUE TITLE
Use character entity reference or character directly in spec

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#381]
In the spec, there are a number of MathML examples that contain non-ascii chars. For example, an elementary math example has `&#xD7;` which is `×`. I think we (at least partially) did this because we couldn't count on browsers to deal with non-ASCII chars properly. I think that concern is long past. There are some cases such as `&#x2061;` where the character is invisible (and hence ambiguous). In those cases, I would recommend we keep using the character entity reference. For the others, I think we should change them to be the character.

**Comment by davidcarlisle** [comment]
In some parts of the spec I intentionally varied between using the character and a reference. 

I think the reason for using references is not so much worry whether the browsers support the character (if they do not, the reference probably won't work either). More, it is some ways more informative for the reader.

If I say use `&#x2192;` to get  `→`  then it's clear how to enter that.

If I say use `→` to get `→` it's possibly less clear how you actually get an arrow, depending on  your input methods.

Could also say to use `&righarrow;` but that's trickier if you are using XML rather than HTML

**Comment by NSoiffer** [comment]
I'm referring to the examples/sample renderings.  For example from F.5.2 Quantifiers (first search result from where I was at):
```
<mrow>
  <mo>&#x2200;</mo>
  <mrow>
    <mrow><mi>p</mi><mo>&#x2208;</mo><mi mathvariant="double-struck">Q</mi></mrow>
    <mo>&#x2227;</mo>
    <mrow><mi>q</mi><mo>&#x2208;</mo><mi mathvariant="double-struck">Q</mi></mrow>
    <mo>&#x2227;</mo>
    <mrow><mo>(</mo><mi>p</mi><mo>&lt;</mo><mi>q</mi><mo>)</mo></mrow>
  </mrow>
  <mo>.</mo>
  <mrow>
    <mo>(</mo>
    <mrow><mi>p</mi><mo>&lt;</mo><msup><mi>q</mi><mn>2</mn></msup></mrow>
    <mo>)</mo>
  </mrow>
</mrow>
```
I think the sample presentation would be much easier to understand if `&#x2200;` etc., were the actual chars.

**Comment by davidcarlisle** [comment]
@NSoiffer  it depends on why anyone is reading the example I suppose.  `∀` looks nicer than `&#x2200;` but

> type `<mo>&#x2200;</mo>` to get `∀`

Is an instruction anyone can follow but


> type `<mo>∀</mo>` to get `∀`

is slightly tautologous and may not actually help anyone to enter the character (other than cutting and pasting it from the text)

But if all examples use character references it gives the wrong impression that MathML has to be written as ascii, So as I said above, I was intentionally inconsistent when I edited some examples in Chapter 4. That F.5 qualifier section has two for-all examples, so is an ideal candidate for inconsistency.... 

For the record, due to the way the examples are unescaped, any of the following may be used in the source file, 

   `&amp;#x2200;`   produces `&#x2200;`   
    `&#x2200;`   produces `∀`  
    `∀`   produces `∀`   
    `&amp;forall;`   produces `&forall;`   
     `&forall;` produces `∀`  but makes the source not well formed XML (respec does not care, but I do:-)



That "sample presentation" example is incorrectly marked `<div class="example mathml mml4c">`  not `mml4p`  (probably my error on the initial pass classifying examples) so the inline rendering is not shown. All 5 of the above forms would produce ∀ in the rendered mathml output, if we showed it.

**Comment by NSoiffer** [comment]
The tautology example, while important to pay attention to, seems to be a red herring. Is there any case where it is applicable in the spec?

I also don't understand why intentional inconsistency is a good thing for the spec. I wish it were since that would give me a good excuse when someone points out something I did one way in one place and a different way in a different place :-)

Since no one else is chiming in on this thread and you and I appear to have different opinions and there is no clearly right or wrong, I guess we should ask people on the call this week about their opinions.

**Comment by davidcarlisle** [comment]
>  Is there any case where it is applicable in the spec?

I obviously didn't make myself clear there as It seems to  me to be applicable to all the examples 

to take a spec example

https://w3c.github.io/mathml/#examples-12

shows that you can type  `<mo> &int; </mo>`  to get  ∫  . We could change that and show that you could use `<mo>∫</mo>`  to get ∫  but that does then leave the question of how you type  `<mo>∫</mo>`

> I also don't understand why intentional inconsistency is a good thing for the spec.

It is "showing examples of all legal input forms" You can't do that if you consistently use the same form in all cases. I don't think it is a bad  thing if one example uses  `<mo> &int; </mo>`  and another uses `<mo> &#x222b; </mo>`  and another uses `<mo>∫ </mo>`

**Comment by NSoiffer** [comment]
This is a spec about MathML, not text entry or XML equivalents. Using `&int;` is relatively clear that it is an integral sign, but it isn't valid in many parsers because "&int;" will not necessarily be known. The hex or decimal forms for characters are relative gibberish for most readers. I think we want to make the examples as clear as possible and using the actually characters does that IMHO.

**Comment by polx** [comment]
I am all for using characters instead of entity-references.
Entity references are parts of the failure of the ubiquity of XML: the fact that you may need to parse  DTD (that says something surprise) has made such small examples invalid.

Now that UTF-8 has won in ubiquity and it is rare that such signs are not displayed on modern OS (that is a real progress since the first decade of 2000), there is no big worry in only showing the characters `<mo>∫</mo>`: it can be read and it can be copied. Both were doubtful in the first decade of 2000.

**Comment by davidcarlisle** [comment]
@NSoiffer  @polx  OK, I'm not entirely convinced, but not not prepared to argue the point either:-)

In Chapter 4 which mainly uses numeric character references it is just a matter of globally deleting `amp;`  but in chapter 3 if we do that, `&amp;int;` will become `&int;` which will work in respec html but make the sources not well formed so kill XML tools checking the files (exactly the issues you both mentioned:-) I have a script somewhere that expands these entity references I'll dig it out and run it over the sources, adding some special cases so the invisible characters stay as references.

**Comment by polx** [comment]
The suggestion was to expand the entities in the sense that they are stored as UTF-8 characters.
No numeric or named references at all, except when maybe mentioning that they exist. So &amp;int should not appear anymore.

There has been some beliefs that is good practice to actually differentiate `&int;` and `∫`... I think we agree that these should be disappearing.

**Comment by davidcarlisle** [comment]
this is mostly addressed in 2fcac9bf54778725f6d1c1bcf8d72a0c53839ce3

**Comment by brucemiller** [comment]
I'm inclined to feel that where we are displaying the escaped XML, as in a MathML example, we probably want to display the escaped numeric (but not named) entity as well; that is, show the examples in plain ASCII.  OTOH, where we're showing the result, ie where the browser has actually rendered as MathML, then it should of course render the unicode as well.

**Comment by davidcarlisle** [comment]
Currently (after the last round of commits) the respec sources use Numeric Character References in the escaped verbatim MathML code listings, resulting in the characters being shown in the document, the exception being white space and invisible characters which use escaped NCR in the source, and so appear as an NCR, usually with an entity name as a comment, in the document listing (and as whitespace in the rendered mathml).

This convention was implemened by editing the source, not being forced by the scripting, so some examples could be edited to show Numeric or Entity references, which would be my slight preference, but not something that needs to be done now (or ever).

I suggest this is closed now?

**Comment by NSoiffer** [comment]
Agreed
