### ISSUE TITLE
Intent: location/arrangement of names

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#410]
We need to figure out what should be done with "core" and "open" intent names.

Right now, they are in a [google sheet](https://docs.google.com/spreadsheets/d/1EsWou1K5nxBdLPvQapdoA9h-s8lg_qjn8fJH64g9izQ/edit#gid=1358098730).
* Is this the final location or a temporary until something better is used?
* Is the current arrangement correct -- units and names for all the operators (#255) still need handling

This issue is mainly a placeholder right now so it can be pointed to from the spec.

**Comment by davidcarlisle** [comment]
As discussed In the call yesterday, a sketch of a format for a Core Concept list is at

https://mathml-refresh.github.io/intent-lists/core/

Since the call  I added  a language selector so initially it shows English speech templates but you can also show "French" or both (using whatever OS-specific interaction you need on a standard html multi option selector). Just enough French to test the text was changing, it's not complete and probably not correct.

I had used markdown rather than html for the source here to keep things simple, especially for the sibling Open List

https://mathml-refresh.github.io/intent-lists/open/

But markdown table support is gruesome: all entries need to be on the same line in the source, so by the time you add several languages, keeping track of which entry to edit is hard.  If we decide to use a final display something like this, we could use html source or some custom markup and a github action to do whatever is needed to merge the entries

**Comment by NSoiffer** [comment]
I think it would be better to put the language selector in the header cell for the speech template since that is the only column that changes when the language is changed.

**Comment by davidcarlisle** [comment]
certainly it needs some better styling, but doing anything fancy inside the table is hard while the source is markdown. as you can show both languages at the same time it would need to be on a spanning entry and you can't do that in markdown I think

**Comment by davidcarlisle** [comment]
@NSoiffer I replaced the markdown table with a table generated from YAML which gives a lot more flexibility and allows easy addition of new languages


language list:

https://github.com/mathml-refresh/intent-lists/blob/main/docs/_data/languages.yml

Core  list source:

https://github.com/mathml-refresh/intent-lists/blob/main/docs/_data/core.yml

there is a column for each listed language, if any speech template does not have a translation the english text is used with a suffix of the language code.

The list of languages is copied from another project and would need tuning

**Comment by davidcarlisle** [comment]
> I think it would be better to put the language selector in the header cell for the speech template since that is the only column that changes when the language is changed.

html multi selectors are a bit weird: an alternative UI with checkboxes I think makes it clearer how to select multiple languages

https://mathml-refresh.github.io/intent-lists/core/index2.html

**Comment by NSoiffer** [comment]
That's too bad it is hard. I still think the selector leads one to think
all the columns potentially change (ok, some are fixed to English because
they are predefined names), but I would expect comments would get changed
with the current setup.

Can't you make it an "n+5" column table and add some JS that makes the
"n-1" non-selected columns hidden so the display is not affected? You
aren't stuck with plain HTML...

    Neil

**Comment by davidcarlisle** [comment]
Both core and open list sources are now yaml so  there is a lot more flexibility over the table layout  than when it was a markdown table. That said, I don't currently see an easy way of styling the choice within columns that may come and go. Also as you say it might be natural to make the comments language specific, which would be trivial to do with the current layout.

I'd rather leave the styling a bit until the content is clearer. especially the open list is a bit incoherent semi-automatically derived from the original Google docs sheets.

**Comment by davidcarlisle** [comment]
agreed to use https://w3c.github.io/mathml-docs/intent-core-concepts/
