### ISSUE TITLE
Syntax of isa and hint

### ISSUE THREAD

**Issue by brucemiller** [w3c/mathml#436]
Now that we're creeping up on general agreement about the utility
of isa and hints, I have a few questions which might help us agree
on a concrete syntax (at risk of irritating those who thought this was Settled).

I'll assume there are use cases for an element's intent to:
* assert *both* a hint and an isa   (and order shouldn't matter);
* assert a non-core isa;
* assert more than one isa (particularly if a non-core isa is more specific).

Are hint and isa so distinct and likely to be confused that they really deserve distinct syntaxes?
Hints are kinda like isa; and any term that is not `prefix|infix|postfix|function|silent` can be assumed to be an isa.

Let me suggest that we choose a single character ("@", ":", I don't particularly care what), and combine isa & hint into a single syntax that allows repeats.

I might go a step further and define `concept-or-literal` to include the hint/isa,
rather than only allow hints on applications, and allow the name part to be empty.
This avoids the need to introduce a keyword "this". (I'll come up with a grammar,
if anybody is interested).

A bad example where we do NOT specify what "*" is, figuring "star" is good enough,
but still provide some useful annotation:
```
<mo intent=":infix:linear-operator">*</mo>
```

**Comment by dginev** [comment]
### Self-referential keyword

There were several rounds of email conversations about the grammatical introduction of an "empty head" syntax, which had different kinds of appeal at different stages of the intent grammar.

Currently, I have two technical reservations that make me worry about the empty head, which I don't have for named alternatives. My preference leans towards reserving `$this`, `$self`, `this` or `self` (or all 4) as dedicated keywords that stand for "the current node". This preference is motivated by an expectation that the syntax is already familiar from a wide range of programming languages, and from observing a current trend where keywords are easier/more appealing to learn than sigils (such as `*`). 

The `*` is the other suggestion with some traction, currently preferred by David C.

---

1. An empty intent is technically confusing to learn about and use, knowing that we also have a silent underscore intent `_`.

   Compare:
   ```html
   <mrow intent=":rational-number">
     <mo>-</mo>
     <mi>x</mi>
   </mrow>
   ```
   Here, AT ought to read the mrow as "negative x" (the "accessible name") and have the type "rational-number" available as an "accessible description".

   and also:
   ```html
   <mrow intent="_:rational-number">
     <mo>-</mo>
     <mi>x</mi>
   </mrow>
   ```

   Here, AT ought to remain silent for this entire expression, possibly having the accessible description available - but maybe just hiding everything.

   It is a source of confusion that the invisible empty head will lead to the node being spoken (as if there was no annotation), while the inked `_` intent will lead to the node being silent/skipped. If we did not have the `_` intent, then introducing an empty value would have been more intuitive.

2. My second reservation is creating a class of grammatical artifacts that would otherwise look malformed, such as:
   ```html
   <mi intent="(,,)">x</mi>
   ```
   which contains 4 empty values. Would we have to decide if this implies the speech "x of x,x and x"? 

   It is tempting to stay in a realm where that expression is not supported by the official intent grammar.

### Hints and Is-a

Keeping them apart for now allows for fleshing them out separately, and deciding if each feature is needed.

Specifically when it comes to having "multiple is-a" annotations, I am unsure if we can reasonably expect AT to provide a good accessible description by simply concatenating them all together. Even the basic is-a proposal allows for stacking them, though we haven't discussed if that enables any meaningful features, and if AT would be interested to support stacking. As usual, it can be accomplished by adding more `mrow` elements. Here is one "type hierarchy" example:

```xml
<mrow intent="$c1:operator">
  <mrow intent="$c2:arithmetic-operator" arg="c1">
    <mrow intent="$c3:commutative-operator" arg="c2">
      <mrow intent="$c4:associative-operator" arg="c3">
        <mo intent="plus" arg="c4">+</mo>
     </mrow></mrow></mrow></mrow>
```

**Comment by davidcarlisle** [comment]
@brucemiller  

> I might go a step further and define concept-or-literal to include the hint/isa,
rather than only allow hints on applications

I actually did that "naturally" in some of my examples before Neil pointed out it wasn't valid.

`<mo intent="plus@infix">+</mo>`

seemed a reasonable "explicit default" to me.

As for combining isa and hints. I'm not sure, seems a radical suggestion but not imposible, you would though have to allow multiple hints, as you show.

Deyan  not unreasonably objected to `(,,)` but you could allow empty heads without that, ensuring that one of head or isa/hint  is present, something like `head(:isa)* | (:isa)+`

but I'm not sure if a hint of `prefix` is really the same kind of thing as an isa giving a "mathematical type" but worth making some examples and see how it looks.

**Comment by brucemiller** [comment]
*So* many points!

@davidcarlisle My thinking was that `hint` and `isa` are similar, being properties of an object; rather than identical, restricted kinds of properties as "mathematical type" suggests.  Thus my question was whether we need to put that fine a point on it?

@dginev I personally wouldn't find it confusing that `intent="_:foo"` is different than `intent=":foo"`, although I'll grant the "_" might be easy to overlook when your eyes are fading.

@davidcarlisle I'm not so fond of `*` as it so strongly carries the glob sense of matching all.  If we use `*`, it should probably reserved for one of those forms you've suggested to match all children, all rows, or such --- although, regrettably, so far I haven't liked any specific proposal.

@dginev Indeed many languages have a `this` or `self`, but it's consistently used as a reserved identifier in the place of a normal identifier; that is, `self` or `x` both refer to some lexically visible object.  Using `self` in the head, in place of a Concept Name is logically inconsistent. OTOH, using `$self` as a reference is logically consistent, but if used outside the head would lead to to circular intents.

@dginev regarding `intent="(,,)"`: Short answer: we can always forbid empty intents.
Confusing answer: I wasn't thinking of the empty head `intent=":foo"` as *necessarily* applying properties to a self, rather simply supplying properties *without* supplying a concept at all.  Thus, `intent=":foo"` might indeed apply the property `foo` to self, but `intent="something(:foo)"` would amount to "something of a foo" (likely useless, but ...).

**Comment by brucemiller** [comment]
@dginev rightly pointed out that we already allow, with some mind-boggling scaffolding, multiple hints, and the same trick would allow multiple isa.  And wonders how it should be interpreted.

Unless we decide this is a really bad thing and want to make it as hard as possible, perhaps allowing it in the syntax might be a good thing?

I wasn't thinking of contradictory hints, like `intent="foo@infix@prefix@postfix"`.  I suppose we'd want to clarify that last (or first) one wins?  I was thinking more of levels of detail like `intent="foo:matrix:tridiagonal-matrix"`,  where (perhaps) `matrix` is a type known to core and all AT, but `tridiagonal-matrix` is a type from (the|a) open list and might only be known to a few.  Generally: if you know the isa, use it, otherwise ignore it.

**Comment by dginev** [comment]
> OTOH, using $self as a reference is logically consistent, but if used outside the head would lead to to circular intents.

See the `<mtable intent="matrix($this)">` comment [here](https://github.com/w3c/mathml/issues/426#issuecomment-1437308818) for a non-circular example of a case where having such identifiers is useful. Another example would be some expedient language padding, as in
```xml
<mrow intent="_(_the, $this)">
  <mo>-</mo>
  <mi>x</mi>
</mrow>
```
to force a reading of "the negative x" (or similar, "the" being forced).

A good benefit of a reserved keyword is that when circularity is written down (one would assume - by mistake) it can be obvious where that happened upon review. Compare `intent="$this($this)"` to `intent="*(*)"` or possibly the worst offender: `intent="()"`.

**Comment by brucemiller** [comment]
Sorry, to *me* the markup `<mtable intent="matrix($this)">...` should be spoken as "matrix matrix matrix ...".  Unless, as it seems, you're intending `$this` to mean "the speech that would have been generated without `intent`".  Maybe such a thing is useful, but it hardly should mimic OOP's  `this` or `self`, it's more like the internal representation of the object (a struct or hash...)

**Comment by davidcarlisle** [comment]
@brucemiller 
 > Sorry, to me the markup `<mtable intent="matrix($this)">`... should be spoken as "matrix matrix matrix ...".

Any description of `$self/$this` would need to say explicitly that it references "what you would have done with no intent" which is one advantage of using `*` rather than `$this` as  it allows an alternative connotation of "children" rather than "self" so `matrix(*)`  on an mrow picking up `( mtable )` rather than being a self ref to the mrow. 

But I fear this is going to be a source of bugs and am warming to the empty head idea so  `intent="@matrix"` 

 If you  (or rather I) think of `matrix` as a mathematical type it seems a long way from the "hint" idea but really I think you are right: I don't care about the mathematical properties here, I  just want "read it row by row like a table" which is a layout/voice hint not so different  from  `@suffix` "read the operator after the argument"

Which would lead to a grammar something like

```
intent             := term property* | property+ | application 
term               := concept-or-literal | number | reference 
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent '(' arguments? ')'
arguments          := intent ( ',' intent )*
property           := '@' NCName
```

which adds `property` as a combined isa/hint feature and still ends up being simpler than the current grammar.

That  allows the head or property list to be empty, but not both. If we wanted to allow completely empty subterms so   
`intent="()()((,,,))"`   
the first line could be simplfied to

```
intent             := term? property* | application 
```
But  I suspect that's a generalisation too far.

But with a `$self` (either reserved or by allowing arg="self" on the element to be in scope) and not allowing empty head, first line is simpler still:


```
intent             := term property* | application 
```

**Comment by dginev** [comment]
@brucemiller 
> you're intending $this to mean "the speech that would have been generated without intent". Maybe such a thing is useful

Exactly. I am particularly fond of borrowing the javascript intuition. In one of the contexts where `this` has defined behavior [w3cshools quote](https://www.w3schools.com/js/js_this.asp), it refers to the current element:
> In an event, `this` refers to the element that received the event.

This is loosely sharing the object-oriented intuition, where `self` is often used to refer to the implied object/data which received a method call.

@davidcarlisle 
> Any description of $self/$this would need to say explicitly that it references "what you would have done with no intent" 

Agreed. That adds clarity.

**Comment by brucemiller** [comment]
I'm not  so fond of `$this`, but could accept the special case, if it simplifies things and others prefer it.

I *am* gradually becoming more fond of ":" as the property indicator, rather than "@".

And, as long as we're scavenging other languages for parts... have we rejected child references, lately?
We could borrow from the various shells that `$1, $2, ...` refer to the first, second, etc child; But also that `$0` is equivalent to `$self` (in the special sense), and that `$@` could refer to the list of (all!) children (if we decide that's needed).

That would simplify much of the annotation in the lists. And as long as we avoid xpath-y references, it wouldn't seem to put undo burden on rearrangements.

**Comment by davidcarlisle** [comment]
> I'm not so fond of `$this`, but could accept the special case, if it simplifies things and others prefer it.

I'm not that keen on it either, if we have it I'd prefer to not fix the name and just allow `$ref` to find arg="ref" on the current element not just descendents, so widen the scope of arg ref, not have a magic keyword that looks like a  reference.
> 
> I _am_ gradually becoming more fond of ":" as the property indicator, rather than "@".

My worry is that it looks close to a namespace reference then, `<m:mrow intent="something:else">` but that's only a mild concern, `:` would work.

> 
> And, as long as we're scavenging other languages for parts... have we rejected child references, lately? 

About 2 years ago, I'd worry about cycling that far back if we are ever to get this done.

> We could borrow from the various shells that `$1, $2, ...` refer to the first, second, etc child; But also that `$0` is equivalent to `$self` (in the special sense), and that `$@` could refer to the list of (all!) children (if we decide that's needed).
> 

getting a useful definition of child in the face of implicit mrows and polyfills moving things around to fake mfenced killed off positional references last time, and I'm not sure anything has changed

> That would simplify much of the annotation in the lists. And as long as we avoid xpath-y references, it wouldn't seem to put undo burden on rearrangements.

Hmmm :-)

If I have 

`<mfenced intent="open-interval($1,$2)"><mi>x</mi><mi>y</mi></mfenced>`  

is that going to work if javascript is making a dom 

`<mrow intent="open-interval($2,$4)"><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo></mrow>`

Obviously it _could_ be made to work but...

**Comment by brucemiller** [comment]
"mfenced"? What's that??  Ah, yes polyfills.  Feel free to consider the proposal "recently rejected"

**Comment by NSoiffer** [comment]
I'm joining the party a little late, but here's my thoughts:

1. I'm glad the $number idea is "recently rejected". Too fragile.
2. I'm not keen on mixing hints and types. One way you could imagine a type being presented to a user is as a popup or speech via hover or focus. Getting the information that something is a matrix or integer could be helpful. Getting the information that it is infix or prefix would be rather nonsensical in most cases. For example, hovering over $x^T$ and hearing "matrix" might be useful. Hearing "postfix" because you wanted it spoken as "x transpose" is perplexing.
3. My concern with "self" and "this" is that (I think) the discussion is focused on it meaning "my children", which is not the meaning of "self" and "this" in programming languages, so it is potentially more confusing than picking something like "child" or "children" (or both since sometimes one is more natural than the other) or maybe "contents".
4. I like `*` for meaning all the children. But if it shows up in the head, it is very confusing. So I'm not a fan of that.
5. I concur with those that worry about hard to spot bugs or hard to understand notations like `intent="(,,)"`. @dginev showed me something he wrote a few years back about a goal that what we come up with should be intuitive, and that is anything but intuitive. So I'd like to see a syntax such as what @davidcarlisle proposed that avoids it (although I don't agree with the details of the one he listed due to lumping hints and types together)

One of the bugs I had in my implementation comes from something I wrote by accident:
```
<mi intent="$my-arg:int" my-arg="x">x</mi>
```
I wrote this to avoid repeating the contents as the intent head. I.e., 
```
<mi intent="x:int" my-arg="x">x</mi>
```
because using it as the head violates the "don't repeat yourself" principle (same info in two places). The spec says
> An argument [reference](https://w3c.github.io/mathml/spec.html#intent_reference) such as $name refers to a descendant element that has an attribute arg="name".

so it doesn't really do what I want without a special case rule.

For what I wanted, we either need a legal empty head or a way to refer the descendants, which could be text and hence not able to be referenced via "$". Potentially saying that a self reference is a special case is a solution, but I think it is like using "self" in that it the self reference refers to the entire element, not a decedent. So it is not intuitive

**Comment by davidcarlisle** [comment]
> I'm joining the party a little late, but here's my thoughts:
> 
 
>     2. I'm not keen on mixing hints and types. One way you could imagine a type being presented to a user is as a popup or speech via hover or focus. Getting the information that something is a matrix or integer could be helpful. Getting the information that it is infix or prefix would be rather nonsensical in most cases. For example, hovering over xT and hearing "matrix" might be useful. Hearing "postfix" because you wanted it spoken as "x transpose" is perplexing.

ah if the type is used for driving more than the speech, merging with hints is problematic I agree.
Shame though; I was a bit surprised by @brucemiller's suggestion on first reading but was warming to it.

> 
>     3. My concern with "self" and "this" is that (I think) the discussion is focused on it meaning "my children", which is not the meaning of "self" and "this" in programming languages, so it is potentially more confusing than picking something like "child" or "children" (or both since sometimes one is more natural than the other) or maybe "contents".

well we have been using it for both really: if you have

`<mfrac intent="?:something-not-a-fraction"><mi>a</mi><mi>b</mi></mfrac>`

where `?` is `$this`  or `$self` or `*` or empty or whatever, then really it refers to the $\frac{a}{b}$ construct not just the children $ab$ out of context. But still  I prefer `*` over other suggestions (I think)


> 
>     4. I like `*` for meaning all the children. But if it shows up in the head, it is very confusing. So I'm not a fan of that.

see above:-)

> 
>     5. I concur with those that worry about hard to spot bugs or hard to understand notations like `intent="(,,)"`. @dginev showed me something he wrote a few years back about a goal that what we come up with should be intuitive, and that is anything but intuitive. So I'd like to see a syntax such as what @davidcarlisle proposed that avoids it (although I don't agree with the details of the one he listed due to lumping hints and types together)

Yes agreed empty arguments is (perhaps) possible, but allowing empty head is weird, not allowing either is probably best unless we find a real use case for `foo(a,,)`

> 
> 
> One of the bugs I had in my implementation comes from something I wrote by accident:
> 
> ```
> <mi intent="$my-arg:int" my-arg="x">x</mi>
> ```
> 
> I wrote this to avoid repeating the contents as the intent head. I.e.,
> 
> ```
> <mi intent="x:int" my-arg="x">x</mi>
> ```
> 
> because using it as the head violates the "don't repeat yourself" principle (same info in two places). The spec says
> 
> > An argument [reference](https://w3c.github.io/mathml/spec.html#intent_reference) such as $name refers to a descendant element that has an attribute arg="name".
> 
> so it doesn't really do what I want without a special case rule.

yes as I comment above if we want `$self` I think we should change the rules to allow exactly that, starting the search for mathing arg="self" on the current element, together with some wording about avoidig cyclic interpretion. but  prefer a special syntax such as `*`
> 
> For what I wanted, we either need a legal empty head or a way to refer the descendants, which could be text and hence not able to be referenced via "$". Potentially saying that a self reference is a special case is a solution, but I think it is like using "self" in that it the self reference refers to the entire element, not a decedent. So it is not intuitive

If you allow * and separate hint and properties and just allow at most one of each, you get

```
intent             := term property? hint? | application 
term               := concept-or-literal | number | reference | '*'
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent '(' arguments? ')'
arguments          := intent ( ',' intent )*
property           := ':' NCName
hint               := '@' NCName
```

**Comment by dginev** [comment]
> if we want $self I think we should change the rules to allow exactly that, starting the search for mathing arg="self"

You're just moving the awkwardness to the arg-resolution mechanism though? Consider:
```xml
<mrow arg="self" intent="$self:rational-number">
  <mo>-</mo>
  <mi arg="self" intent="$self:natural-number">x</mi>
</mrow>
```

The currently specified behavior is to match the `$self` reference of the `mrow` to the `self` arg attribute somewhere inside its descendants, in this case the `mi`.

So if you want to have `$self` resolve to the arg of the node hosting it, you would need a special-case exception for how the search for `arg` is performed. This approach is both more complicated, and involves more markup, than simply reserving a keyword (`$self` here) and describing it as "pointing to the current node".

At the least, I would be interested in specifying an "error recovery" strategy for the case where `arg="self"` is missing, where we can advise AT to resolve the error by defaulting `$self` as pointing to the current node. That would be helpful, since someone is bound to make an innocent mistake...

**Comment by davidcarlisle** [comment]
On Wed, 22 Feb 2023 at 00:39, Deyan Ginev ***@***.***> wrote:

> if we want $self I think we should change the rules to allow exactly that,
> starting the search for mathing arg="self"
>
> You're just moving the awkwardness to the arg-resolution mechanism though?
> Consider:
>
> <mrow arg="self" intent="$self:rational-number">
>   <mo>-</mo>
>   <mi arg="self" intent="$self:natural-number">x</mi>
> </mrow>
>
> The currently specified behavior is to match the $self reference of the
> mrow to the self arg attribute somewhere inside its descendants, in this
> case the mi.
>
> So if you want to have $self resolve to the arg of the node hosting it,
> you would need a special-case exception for how the search for arg is
> performed.
>

no, you would just start on the current node, and as now take the first one
in depth first order.  Which would change the interpretation of your
example but presumably change to the intended meaning here.

> This approach is both more complicated, and involves more markup, than
> simply reserving a keyword ($self here) and describing it as "pointing to
> the current node".
>
it takes more markup arg="self" (or any other name the author chooses) but
is less complicated as it needs no new rules. pre-allocating $self  for
example would mean adding a rule making arg="self" invalid as it would not
be referenceable by $self.

> At the least, I would be interested in specifying an "error recovery"
> strategy for the case where arg="self" is missing, where we can advise AT
> to resolve the error by defaulting $self as pointing to the current node.
> That would be helpful, since someone is bound to make an innocent mistake...
>
> no the whole point would be to avoid special casing any name.

Although as mentioned elsewhere I think we need a softer error recovery for
`$foo` if there is no matching `arg="foo"` . it is a bit brutal to reject
the entire expression.

David

**Comment by brucemiller** [comment]
@NSoiffer I don't see how combining `hint` and `isa` is such a problem. The list of `hint` values is short and the AT can easily recognize those and omit those from speech or tooltips.  Separating them complicates the syntax & grammar, and apparently pushes us to choose an odd order and restrict to only a single `isa`(?) (or further complicate the grammar).  I kinda like something like `<mi intent="cm:unit:length">`.

**Comment by brucemiller** [comment]
After watching the discussion & ensuing confusion for awhile, I think I'm coming around to agree with a combination of @dginev 's suggestion of `self` (*without* the sigil `$`) and @davidcarlisle 's suggestion that it is a "syntactic keyword" (that is, explicitly appears in the intent grammar).  At least, if an empty concept is excluded, which I still prefer.

* It is *not* a normal reference, since it ignores self's intent, so the sigil is confusing. Requiring an `arg="self"` just makes it more confusing and complicated.
* Putting it specifically in the grammar makes clear that it is a special keyword and not a concept name (and thus not inconsistent).
* I think that `*` will lead to much confusion about whether it refers to the node itself or its children, particularly given the special casing of ignoring its intent.

**Comment by davidcarlisle** [comment]
allowing multiple properties would be OK  with the grammar I posted above, just change `?` to `*`  I was just thinking you only _needed_ multiple when hints combined so you could have `:length:postfx` but can keep the multiple ones, but you have almost convinced me to prefer combining them. 

I'm not keen on `self` as a keyword as it looks like a concept: intent="Self" and intent="self" would be different grammatical constructs which seems as confusing as other confusions, so.. let's try empty head..


allowing  `:matrix` to give a matrix property on current node but not allowing empty subterms. with or without combining isa and hints

```
intent             := term property* hint? | property+ hint? | application 
term               := concept-or-literal | number | reference 
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent '(' arguments? ')'
arguments          := intent ( ',' intent )*
property           := ':' NCName
hint               := '@' NCName
```

```
intent             := term property* | property+ | application 
term               := concept-or-literal | number | reference
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent '(' arguments? ')'
arguments          := intent ( ',' intent )*
property           := ':' NCName
```

**Comment by dginev** [comment]
Now that the discussion in #435 has progressed as far as it has, I think I can address the original suggestion by @brucemiller with full transparency:

I am **in favor** of Bruce's original suggestion for combining the `@hint` and `:isa` syntaxes, and am leaning towards preferring the colon `:` character.

But I am coming from the standpoint of someone who is likely to avoid using `@hints` in their entirety, so I am weighing the decision entirely from the perspective of "it is good to keep the intent syntax as simple as we can". Having only one of `@` or `:` does reduce the cognitive load of how one thinks of an intent expression.

The question of what to do with "stacked" isa annotations remains open I think. That can also be discussed in #426 , if this issue can benefit from a quick resolution.
