### ISSUE TITLE
white space in intent grammar

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#437]
The current intent grammar is 

```
intent             := concept-or-literal | number | reference | application
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent hint? '(' arguments? ')'
arguments          := intent ( ',' intent )*
hint               := '@' ( 'prefix' | 'infix' | 'postfix' | 'function' | 'silent' )
```

although this issue applies also to variant grammars being discussed in other issues.

The grammar is given in an undocumented but mostly self-explanatory syntax but we have so far avoided mentioning white space.

Presumably? white space is intended to be allowed and ignored between the tokens of the `application` production (I am using visble space here just for clarity, the question is about real white space (space/tab/newline)  so

`foo␣(␣a,␣b␣)`  is the same as `foo(a,b)`

but is `-␣3 ` a _number_  `-3`  and is `$␣foo` a valid _reference_ `$foo` to `foo`  ?

are all these valid?

`foo@prefx`   `foo␣@prefix`    `foo␣@␣prefix`

My instinct would be to not allow space after `-` or `@` (or `:` when we add it) but to allow it elsewhere, in particular before `@` (and `:`)

If that is what we want we could keep the grammar as is and specify white space rules as post-grammatical constraints in words, or we could say white space is not allowed between tokens, then add a white space production to selectively allow it, so something like

```
intent             := concept-or-literal | number | reference | application
concept-or-literal := NCName
number             := '-'? digit+ ( '.' digit+ )?
reference          := '$' NCName
application        := intent S hint? S '(' S arguments? S ')'
arguments          := intent ( S ',' S intent )*
hint               := '@' ( 'prefix' | 'infix' | 'postfix' | 'function' | 'silent' )
S                  :=  [ \t\r\n]*
```

So just opening the issue to check if we do agree on where spaces should be, and suggestions on the best way to specify that

**Comment by dginev** [comment]
The grammar looks less readable with the spacing rules included.

Can't we instead state that `intent` never relies on meaningful spaces, and tools are free to discard all `\s` characters as a sanitization step before processing the intent expression?

**Comment by davidcarlisle** [comment]
@dginev yes  we can give the rules as words rather than sprinkling `S` around, but I don't think saying "free  to discard" is enough, and which spaces are discardable?, is `intent="s␣u␣m"` a valid intent? Also we should mandate discarding  for spaces that are discardable, I don't want `max( x , y )`  to be valid or not depending on whether a system took up its freedom to discard spaces.

testing with mathcat

`max @ postfix( a , b )`  is valid (so allowing space after `@`)

`max @ postfix( $ a , b )`  is invalid (not allowing space after `$`)

I'm OK with those rules, but if that's what we want we need to make it explicit in words or in the grammar.



`- 3` is accepted by mathcat and reads as `-3` (but both read as 3 currently)

`3 4`  is accepted by mathcat (not valid to the grammar ) but reads as 3 4 so not equivalent to `34`

**Comment by dginev** [comment]
Right. My line of thinking was
 - the grammatical intent syntax does not use spaces (ever)
 - we have an advertised "error recovery" where all spaces are silently dropped, and the resulting string is re-evaluated
    - making `intent="s␣u␣m"` indeed work for `intent="sum"`, but as an explicitly recovered error.

**Comment by davidcarlisle** [comment]
@dginev I  really don't like that rule (30 years of guilt for inflicting `\zap@space` on LaTeX:-)

latex 2.09 didn't allow spaces around commas in `[12pt,twoside,fleqn]` options, so around 1993 for latex2e we added it but memory was tight so rather than change the parser we just removed all space first so  `[12pt, twoside, fleqn]` worked but so did unintended options like `[12 pt,two side,fleqn]` (which I still see today, in tex forums), and  also nonsense like `[1  2pt,t wosi de,fle qn]` worse, it (still) causes difficult code paths and hard to trace bugs for packages (introduced decades later when machines were fast enough) that want key=value options such as `[boundingbox=11 22 33 44]` and need the spaces to stay.

**Comment by dginev** [comment]
Really fascinating tale of the `\zap@space` experience, thanks for sharing that! I definitely feel your pain.

>  that want key=value options such as [boundingbox=11 22 33 44] and need the spaces to stay.

If we were using spaces for any legal purpose in the intent values, I would share your conclusion here. But we aren't, so we can breathe a little freer and discard them if we wanted to.

But your example made me also ask the question "will we *ever* think of using spaces?"
And if the answer to that is "yes, we might", then we should start allowing them in the grammar already. E.g. if we said that arguments may be separated by commas *or* spaces, as in `intent="plus(1 2 3)"`, then your `boundingbox` example would be fully applicable.

**Comment by NSoiffer** [comment]
The randomness of what MathCAT accepts/does is a good sign of the chaos that will happen unless the spec is explicit about what to do with spaces. I don't like the idea that "s u m" is the same as using "sum" (`s_u_m` I think is a better repair) , but I do think spaces around delimiters except `$` makes sense. I think of `$xxx` as a token in the same way that `123` is a token. 

> `- 3` is accepted by mathcat and reads as `-3` (but both read as 3 currently)

FYI: that's because an element is created with content `- 3`, but then  `-`, and `_` get converted to space as per the spec for reading (I think). My gut is that an error should occur and the author publicly admonished, but that's my XML background speaking :-).

HTML went the route of specifying how error recovery should happen so that users ended up with predictable results (i.e., all browsers were required to make the same repairs). There is a lot of merit in that, but also a lot of work for writing the spec and for implementers. A middle ground would be to make some informative remarks about what should happen (we would need to decide that) and that a future version of the spec might specify details (based on experience with what happens). That latter part puts a little teeth into the informative remarks.

Lastly, I'm concerned about making `intent` complicated to parse. Right now, it is pretty simple. Adding hints and types were easy. Literals and complex heads were my pain points (literals because they aren't elements, so I had to make up a new element for them and tracking down all the locations where they needed to be included was error prone (maybe I should have turned them into mi/mn/mtext...). Removing all spaces would be a simple repair, but I'm not sure that's a great idea.

**Comment by davidcarlisle** [comment]
I put  a proposal at https://github.com/davidcarlisle/mathml/blob/intent-colon/src/mixing.html#L71 which is close to mathCAT's white space handling.

it allows `@ infix`  and `: unit` but not `$ foo` or  `- 3`  I would suggest that we don't allow spaces after `@` or `:` either, which would allow an alternative way to view the grammar would be to consider `@prefix` as a single token.

**Comment by davidcarlisle** [comment]
the exact details depend on the final grammar chosen, closing this issue as does not apply, as written to current propsals
