### ISSUE TITLE
Simple intent templates

### ISSUE THREAD

**Issue by brucemiller** [w3c/mathml#445]
This PR suggests another approach to intent aiming to explore the simplest syntax which achieves at least the essentials for accessibility.  It is for discussion and to contrast with other ideas #443, #444; I am not necessarily championing this idea.

The idea is a close-to-speech string of words with the addition of
* references to children
* properties of things which we hope to leverage as much as possible.

```
template   = piece (spaces piece)*
spaces       = \s+
piece          = property+ | word property*
word          = literal | reference
literal         = [^\s:]+
property   = ':' NCNAME
reference  = '$' NCNAME
```
Notes:
* use NCNAME or any other semi-restricted set of chars you prefer for identifiers/keywords;
* a piece with only properties asserts the properties on current element;
* using references rather than literals assists in navigation;
* AT can use any properties it recognizes to improve speech & navigation,
  but is free to ignore any others.

There is no explicit concept of Concept, nor explicit support of conversion to content,
although a UA is free to do what it wants.

For speech, the speech generated by references is interpolated in, and the resulting words are spoken in order. The AT can modify the words and order according to properties if it wishes.
Most examples discussed in the other issues are straightforward, with the generated speech fairly obvious:
`infinity`, `sin $x`, `sin pi`, `sin gratuitous text pi`, `$x factorial`, `$x cubed plus $x squared plus $x`, `free $r algebra on $x`, `L 2 of R`.

### Leveraging Properties
Some adaptability of the generated speech can be achieved by use of properties; think of them as generalized speech hints.
For example, given an `:ordinal` property
```
<msup intent="$x to the $n:ordinal power">
  <mi arg="x">x</mi>
  <mi arg="n">n</mi>
</msup>
```
would result in "x to the n-th power".

If we wished to defer choices to the AT, based on context, user profile, whatever, we might think of
```
<msup intent=":power"> ...
```
so that the AT could speak "x to the n-th power" or "x cubed" or whatever it prefers.  Note that ":power" here
is *not* the mathematical concept of exponentiation, but rather a speech hint "speak it like a power".

**Comment by davidcarlisle** [comment]
yes something like that.

I was thinking that for those that need them concept references could be recovered by custom properties
so

`<mi intent=":wikidata-Q26851380">ℝ</mi>`  would tell a system that knew that property convention to look at [wikidata](https://www.wikidata.org/wiki/Q26851380)  Or if you didn't trust AT to pronouce R 

`<mi intent="R:wikidata-Q26851380">ℝ</mi>`

@davidfarmer 's example might be
`intent="L-2:wikidata-Q305936 of R:wikidata-Q26851380"`

**Comment by brucemiller** [comment]
Yes! A nice bit of leveraging :>

**Comment by davidcarlisle** [comment]
Basically that would just identify terms not the argument structure, but in the vast majority of cases so long as the intents were just on the leaves, the argument structure can be inferred from the presentation, and in the other cases there is always `<annotation-xml>`

**Comment by NSoiffer** [comment]
This seems pretty minimal but sufficient _if_ all that we care about is speech.

I don't think we need to worry much about navigation, although there are enhancements to navigation that get easier if structure is known.

FYI: most AT support one mode of navigation. MathPlayer/MathCAT supports three:
1. Character-level: this is wandering around character by character as you might in a math editor. It is a little more painful for someone using a screen reader because you get extra words "in numerator", "out of fraction", etc. Those are (of course) critical for someone who can't see the screen.
2. "Simple" (that's the name I came up with for MathPlayer/MathCAT for this mode): like character-level navigation except that "structures" like fraction, superscripts, roots, are treated as like a character when arrowing left/right. You need to explicitly zoom into them if you want to explore them.
3. "Enhanced" -- navigate by structure so that (for example), you hear the lhs of an expression, then the operator, then the rhs. For a fraction, you would hear the numerator, then the denominator when you zoom into it.  If you want finer grain, you zoom in again.

Most AT does something similar to "simple" navigation. MathCAT infers the structure for "enhanced" navigation (and pattern matching for speech). If `intent` gave the structure, that could be used. It would be less work for some AT since `mrow`s wouldn't need to be inferred.

**Comment by brucemiller** [comment]
For these simple templates, I think that navigation wont be negatively impacted in the cases where the MathML is properly structured (eg. with `mrows`),  the `intent` is placed low, and references are used.  What it loses (and to some extent the other templates) over the functional syntax is the ability to reconstruct a proper tree out of less structured markup.

**Comment by davidcarlisle** [comment]
On the call 2023-03-16 we agreed to close this and consolidate discussion of template variants of  ìntent` in #446
