### ISSUE TITLE
Allow spaces in argument lists

### ISSUE THREAD

**Issue by physikerwelt** [w3c/mathml#460]
If I read 
https://github.com/w3c/mathml/blob/acd47ac46da997dd436a7d3eb07a3ab8c37a10ee/src/mixing.html#L78

correctly, one can write `fun($a,$b)` but not `fun($a, $b)` or 

```
fun( $long-a,
        $long-b)
```
I suggest changing that to
```
 arguments          := intent ( ',' S* intent )*

**Comment by dginev** [comment]
@physikerwelt if you look in the `intent` rule you also see:
```
intent             := S ( term property* | property+ | application ) S 
```

Where the `S` allows  zero or more spaces. So what you want is already grammatical in the current spec. 

The difference from what you are suggesting being that the spaces are "part of" the individual argument, rather than "part of" the arguments rule.

But it is interesting to see you're also requesting grammatical spaces, I hadn't realized they are so popular.

**Comment by physikerwelt** [comment]
Ah, I didn't realize S can be empty.
