### ISSUE TITLE
Questions for AT providers

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#461]
We will have 1 - 3 AT providers at our next meeting. We need to provide some smallish document for them so they understand what we want to do.

We have a [Gap Analysis](https://w3c.github.io/mathml-docs/gap-analysis/), but this is likely too long and somewhat out of date with where we are now with intent names and properties. There are also [slides](https://w3c.github.io/mathml-docs/TPAC-2021/), which is likely a good length but are also out of date (they are based on the gap analysis).

Does anyone have another document we could use? One that is maybe a better starting point?

[updated to include questions by others]
We also need to have some focus on what we would like know from them. Anyone want to propose something more useful than:
1. What do you think of the current proposal?
2. What changes do you think should be made?
3. Would you be willing to implement to implement some version of "intent"?

4. Where and how should we strive for consistency in AT outcomes over MathML ?
   * Examples: Unicode characters, K12 math notations, higher math notations, default rulesets for raw MathML Presentation trees?
   * Is there a preference between "consistently interpreted" versus "consistently vocalized" across AT vendors? (e.g. -x interpreted as "unary minus" vs always vocalized as "negative x").
5. Language variations: there are some language variations that intents will not reach, for example the change of the mode of a verb to "subjonctif" in French, the change of an adjective to feminine if it is known that it is necessary, ... Is this a degree of refinement that it is ok to just ignore or should we try to provide markup to support that? (Unicode does a little bit of that)

**Comment by NSoiffer** [comment]
FYI: I am working on this, so others who are considering working on this might want to hold off for a little bit.

**Comment by NSoiffer** [comment]
I've got a first draft at https://github.com/w3c/mathml-docs/blob/main/intent-explainer/index.md.

**Comment by dginev** [comment]
Re: questions
I would be interested to follow up on the [email thread](https://lists.w3.org/Archives/Public/www-math/2023Feb/0011.html) that raised the suggestion to have AT guests.

Q: Where and how should we strive for consistency in AT outcomes over MathML ? 
   - Examples: Unicode characters, K12 math notations, higher math notations, default rulesets for raw MathML Presentation trees? 
   - Is there a preference between "consistently interpreted" versus "consistently vocalized" across AT vendors? (e.g. -x interpreted as "unary minus" vs always vocalized as "negative x").

Thank you for organizing!

**Comment by brucemiller** [comment]
Nice summary of the situation!  A few comments:

Examples: "x hat" vs "x ... circumflex" though different, are really still both syntactic.

The statement "all AT speaks `x^2` semantically" seems questionable (my pet peeve); and later you're implying that `x^2` is only ambiguous in "higher mathematics". I'm not quite sure how best to express it here, but I think you want to point out
that superscripts (and subscripts) are often ambiguous. (and not necessarily only in higher mathematics).

In the 2nd paragraph of section "Intent", you probably want "THE point 1 comma 2" (else you replace notational ambiguity with natural language ambiguity :> )

There is some confusion in the section "Other Uses of Intent",
but I think I'd leave it off entirely.  You might integrate the 2 sentences about
`:rational` into the last paragraph of section "Intent".

**Comment by polx** [comment]
Little comments to the text:
- In the text: "Most AT" (AT is not defined yet).
- "AT could then speak this as "absolute value of x".: Say the same in French ("valeur absolute de x" and in German "Betrag von x") ? 
- I would even add that we are internally pondering the possibility to maintain an internationalized list of default pronounciations
- add at the end of the search paragraph something such as "Moreover the nearness to a textual rendering may help search engines revealing web-pages with concepts queried by words." (as otherwise, one has the impression that only the content-mathml-oriented-search-engines are goals we have thought about).

I would like to ask the following question to the AT makers:

- language variations: There are some language variations that intents will not reach, for example the change of the mode of a verb to "subjonctif" in French, the change of an adjective to feminine if it is known that it is necessary, ... Is this a degree of refinement that it is ok to just ignore or should we try to provide markup to support that? (Unicode does a little bit of that)

Thanks
Paul

**Comment by NSoiffer** [comment]
Thanks to all for the comments. I have moved the questions for the attendees to my initial comment so they are all in one place.

I think I have addressed everyone's text comments. I removed the "other uses" section as it isn't relevant for AT. I have added a one paragraph "internationalization" section based on Paul's comment. That may need expansion, but we haven't discussed the topic in detail. I also mention we lack experience in how intent will get used in non-English language.

Please take another look and see if I moved in the right or wrong direction.

The [github.io version is here](https://w3c.github.io/mathml-docs/intent-explainer/).

**Comment by polx** [comment]
I corrected the French.
I disagree that automatic translation will work with quality in general, neither live (where you state delay as a problem) or in batch: The lack of context will likely make the translation inappropriate (since this is generally not a sentence which is were automatic translators are trained to). I would at least add the fact that it can be a practical first step.

I like the "however" last sentence. The AT-makers will tell us a bit how they expect the users' usages.

**Comment by cookiecrook** [comment]
@NSoiffer Are there minutes from last week's meeting? If so, please link them here. Thanks.

**Comment by NSoiffer** [comment]
Here are the minutes from the meeting
<https://lists.w3.org/Archives/Public/www-math/2023Apr/>.

**Comment by cookiecrook** [comment]
Direct link to Neil's minutes:
https://lists.w3.org/Archives/Public/www-math/2023Apr/0009.html

Andres' clarification:
https://lists.w3.org/Archives/Public/www-math/2023Apr/0010.html

Thanks for posting.
