### ISSUE TITLE
core concepts of one-letter-symbols?

### ISSUE THREAD

**Issue by polx** [w3c/mathml#472]
We should find a criterion so as to decide when to include core-concepts in the list when the concept is "mostly" described as a single letter.

Examples include: 

- well-known sets such as Z (blackboard-Z), Q, R, C, empty-set or H
- well-known constants such as e, i, pi aleph, or the gamma-function, 

The criterion to decide should enable us to include in the core-intents list what is needed for ATs to help in speaking (at various terse level) and for documentation persons to understand the concept.

Part of the answer includes, if included:

- what is the name of the concept?
- what is the speak-aloud when speaking tersely or in a detailed fashion?
- what are the possible connections to concepts of mathematics as linked or defined in mathml-content, openmath or mathematical texts?

**Comment by dginev** [comment]
A very relevant read here is the wiki page on [Latin letters used in mathematics, science, and engineering](https://en.wikipedia.org/wiki/Latin_letters_used_in_mathematics,_science,_and_engineering). It offers a wealth of examples for conceptual single letter use.

To me it is easy to prefer concept *inclusion* in Core if:
 - a letter is *usually* spoken as its underlying concept in standard practice (e.g. "area" instead of A, "ampere" instead of A, "probability" instead of P). This is [rule 2](https://w3c.github.io/mathml-docs/concept-lists/#guidelines-for-core-list-curation) in the guidelines for curation I drafted a couple of weeks ago.
 - the concept fits in the "pre-university STEM" realm - which is easy to demonstrate with already published materials. This is [rule 3](https://w3c.github.io/mathml-docs/concept-lists/#maintaining-mathml-concept-lists) in the guidelines.

And easy to decide on *excluding* when the opposites of these conditions are met.

For borderline examples, this comes to a design philosophy - are we trying to make the list as small as possible, or as large as possible? That question is the best tie-breaker I can think of:
 - If we want the list to have maximum coverage, borderline examples should be included
 - If we want the list to be the smallest possible kernel of concepts, borderline examples should be excluded

**Comment by davidfarmer** [comment]
I think it is relevant that some of the concepts represented by those
symbols can also be represented in other ways.

For example, the reason blackboard bold was invented was because people
cannot easily draw bold letters.  So, we write blackboard bold instead.
It would not be wrong for an author to use a bold Z for the integers.

Similarly, {} is the empty set.  Literally, a set containing no elements.

So, if those single letters were in core, then a publisher would be guided
for how to mark the intent when the same concepts appear with different
typography.

**Comment by NSoiffer** [comment]
By default, a letter is spoken as a letter. If it is bold or gothic or ..., then just like when it is capitalized, that distinction is likely is mentioned in the speech. Because italic letters are the default in math for variables, they are an exception to that rule.

When the letter has some other meaning and the author wants to express that meaning, then that is when we need to allow them to override that default by providing an intent. So if `P` stands for probability and is meant to spoken as such, then an intent is needed. And since this fits the criteria of being K12, then it goes in core. All this follows @dginev's criteria.

The same is true for a bold Z and a blackboard bold Z.  It they represent the set of Integers and the author doesn't want them spoken as "bold cap z" and "blackboard bold cap z" (or maybe "double struck cap z"), then they need use an intent. Since both forms are spoken the same when they represent the set of integers, they share the same intent. And again, since this fits the criteria of being K12, then it goes in core.

As for e and π, they may have a special meaning, but they don't have special speech. Hence, there is no reason to have an intent for them.

`{}` is likely ambiguous. When used to represent an empty set, it needs an intent to cause it to say "empty set" vs "open brace close brace".

**Comment by polx** [comment]
We agree on the following criteria (2023-09-07):

- pre-university STEM, in a _textbook_ published after year 2000
- the letter has a different pronounciation when read aloud in a formula of  the simple letter pronounciation
