### ISSUE TITLE
Minimal MathML profile

### ISSUE THREAD

**Issue by dani31415** [w3c/mathml#59]
This MathML profile aims to be possible to share MathML between as many applications as possible. The idea is to define subset of the most useful MathML constructions that are shared by all applications.

Some of the target applications might be

- Microsoft Word
- Google Docs
- MathML core profile
- MathType
- 

Other objective of this profile is to define a canonic form for writing formulas that solves:

- How to write parenthesis: mrow vs mfenced
- How to write integrals and express the differential operator
- Etc.

**Comment by davidcarlisle** [comment]
Sorry for the late reply here.

I am not sure of the intention here, or how this would differ from MathML Core https://w3c.github.io/mathml-core/ ?
MathML Core is already a fairly aggressive subset of MathML Full, so I'm not sure that any Minimal profile could remove anything from Core?

Perhaps this issue was opened before the scope of MahML Core was clear, and it could now be closed? But I wanted to ask for clarification before closing.

**Comment by davidcarlisle** [comment]
Closing here, as addressed by MathML Core,. Please re-open or open a new issue on MathML-Core if you think further subsetting from MathML Core would help.
